Compiled from "ModTags.java"
public class com.minecolonies.api.items.ModTags {
  public static boolean tagsLoaded;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> decorationItems;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> pathingBlocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> dangerousBlocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> freeClimbBlocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> tier1blocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> tier2blocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> tier3blocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> tier4blocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> tier5blocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> tier6blocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> mangroveTree;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> extraTree;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> tree;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> concreteBlocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> concreteItems;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> concretePowderBlocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> concretePowderItems;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> colonyProtectionException;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> indestructible;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> oreChanceBlocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> validSpawn;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> mushroomBlocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> hugeMushroomBlocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> fungiBlocks;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> fungi;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> compostables;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> compostables_poor;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> compostables_rich;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> meshes;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> floristFlowers;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> excludedFood;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> breakable_ore;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> raw_ore;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> poisonous_food;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> rawMeat;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> feed;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> leather;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.entity.EntityType<?>> hostile;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.entity.EntityType<?>> mobAttackBlacklist;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.entity.EntityType<?>> raiders;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.entity.EntityType<?>> freeToInteractWith;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.item.Item> ignoreNBT;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.biome.Biome> coldBiomes;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.biome.Biome> temperateBiomes;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.biome.Biome> humidBiomes;
  public static final net.minecraft.tags.TagKey<net.minecraft.world.level.biome.Biome> dryBiomes;
  public static java.util.List<net.minecraft.tags.TagKey<net.minecraft.world.level.biome.Biome>> cropBiomeTags;
  public static final java.util.Map<java.lang.String, net.minecraft.tags.TagKey<net.minecraft.world.item.Item>> crafterProduct;
  public static final java.util.Map<java.lang.String, net.minecraft.tags.TagKey<net.minecraft.world.item.Item>> crafterProductExclusions;
  public static final java.util.Map<java.lang.String, net.minecraft.tags.TagKey<net.minecraft.world.item.Item>> crafterIngredient;
  public static final java.util.Map<java.lang.String, net.minecraft.tags.TagKey<net.minecraft.world.item.Item>> crafterIngredientExclusions;
  public static final java.util.Map<java.lang.String, net.minecraft.tags.TagKey<net.minecraft.world.item.Item>> crafterDoIngredient;
  public static void init();
}
