Compiled from "ICitizenData.java"
public interface com.minecolonies.api.colony.ICitizenData extends com.minecolonies.api.colony.ICivilianData,com.minecolonies.api.quests.IQuestGiver,com.minecolonies.api.quests.IQuestParticipant {
  public static final int MAX_SATURATION;
  public abstract void onRemoveBuilding(com.minecolonies.api.colony.buildings.IBuilding);
  public abstract com.minecolonies.api.colony.buildings.IBuilding getHomeBuilding();
  public abstract void setHomeBuilding(com.minecolonies.api.colony.buildings.IBuilding);
  public abstract com.minecolonies.api.colony.buildings.IBuilding getWorkBuilding();
  public abstract com.minecolonies.api.colony.jobs.IJob<?> getJob();
  public abstract void setJob(com.minecolonies.api.colony.jobs.IJob<?>);
  public abstract <J extends com.minecolonies.api.colony.jobs.IJob<?>> J getJob(java.lang.Class<J>);
  public abstract void setLastPosition(net.minecraft.core.BlockPos);
  public abstract net.minecraft.core.BlockPos getLastPosition();
  public abstract void setSaturation(double);
  public abstract boolean isAsleep();
  public abstract net.minecraft.core.BlockPos getBedPos();
  public abstract void setAsleep(boolean);
  public abstract void setBedPos(net.minecraft.core.BlockPos);
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenHappinessHandler getCitizenHappinessHandler();
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenMournHandler getCitizenMournHandler();
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenSkillHandler getCitizenSkillHandler();
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenDiseaseHandler getCitizenDiseaseHandler();
  public abstract void scheduleRestart(net.minecraft.server.level.ServerPlayer);
  public abstract boolean shouldRestart();
  public abstract void restartDone();
  public abstract void setIsChild(boolean);
  public abstract boolean justAte();
  public abstract void setJustAte(boolean);
  public abstract boolean isIdleAtJob();
  public abstract com.minecolonies.api.entity.ai.JobStatus getJobStatus();
  public abstract void setJobStatus(com.minecolonies.api.entity.ai.JobStatus);
  public abstract java.util.Optional<com.minecolonies.api.entity.citizen.AbstractEntityCitizen> getEntity();
  public abstract com.minecolonies.api.entity.citizen.VisibleCitizenStatus getStatus();
  public abstract void setVisibleStatus(com.minecolonies.api.entity.citizen.VisibleCitizenStatus);
  public abstract net.minecraft.core.BlockPos getStatusPosition();
  public abstract void setStatusPosition(net.minecraft.core.BlockPos);
  public abstract java.util.Random getRandom();
  public abstract void applyResearchEffects();
  public abstract void onGoSleep();
  public abstract void setNextRespawnPosition(net.minecraft.core.BlockPos);
  public abstract boolean needsBetterFood();
  public abstract com.minecolonies.api.colony.ICitizenData getPartner();
  public abstract java.util.List<java.lang.Integer> getChildren();
  public abstract java.util.List<java.lang.Integer> getSiblings();
  public abstract com.minecolonies.api.util.Tuple<java.lang.String, java.lang.String> getParents();
  public abstract void addSiblings(java.lang.Integer...);
  public abstract void addChildren(java.lang.Integer...);
  public abstract void setPartner(int);
  public abstract void onDeath(java.lang.Integer);
  public abstract void setParents(java.lang.String, java.lang.String);
  public abstract void generateName(java.util.Random, java.lang.String, java.lang.String, com.minecolonies.api.colony.CitizenNameFile);
  public abstract boolean isRelatedTo(com.minecolonies.api.colony.ICitizenData);
  public abstract boolean doesLiveWith(com.minecolonies.api.colony.ICitizenData);
  public default void setWorking(boolean);
  public default boolean isWorking();
  public abstract void onResurrect();
  public default boolean hasCustomTexture();
  public abstract void setCustomTexture(java.util.UUID);
  public abstract java.util.UUID getCustomTexture();
  public abstract void setIdleDays(int);
  public abstract void onQuestCompletion(net.minecraft.resources.ResourceLocation);
  public abstract void onInteractionClosed(net.minecraft.network.chat.Component, net.minecraft.server.level.ServerPlayer);
  public abstract void onBuildingLoad();
  public abstract void setInteractedRecently(java.util.UUID);
  public abstract boolean hasQuestAssignment();
  public abstract net.minecraft.core.BlockPos getHomePosition();
  public abstract double getDiseaseModifier();
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenFoodHandler getCitizenFoodHandler();
  public abstract int getLeisureTime();
  public abstract void onRequestCompleted(com.minecolonies.api.colony.requestsystem.token.IToken<?>);
}
