Compiled from "IColonyManager.java"
public interface com.minecolonies.api.colony.IColonyManager {
  public static com.minecolonies.api.colony.IColonyManager getInstance();
  public abstract com.minecolonies.api.colony.IColony createColony(net.minecraft.server.level.ServerLevel, net.minecraft.core.BlockPos, net.minecraft.world.entity.player.Player, java.lang.String, java.lang.String);
  public abstract void deleteColonyByWorld(int, boolean, net.minecraft.server.level.ServerLevel);
  public abstract void deleteColonyByDimension(int, boolean, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract void removeColonyView(int, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract com.minecolonies.api.colony.IColony getColonyByWorld(int, net.minecraft.world.level.Level);
  public abstract com.minecolonies.api.colony.IColony getColonyByDimension(int, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract com.minecolonies.api.colony.buildings.IBuilding getBuilding(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract com.minecolonies.api.colony.IColony getColonyByPosFromWorld(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract com.minecolonies.api.colony.IColony getColonyByPosFromDim(net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>, net.minecraft.core.BlockPos);
  public abstract boolean isFarEnoughFromColonies(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract java.util.List<com.minecolonies.api.colony.IColony> getColonies(net.minecraft.world.level.Level);
  public abstract java.util.List<com.minecolonies.api.colony.IColony> getAllColonies();
  public abstract java.util.List<com.minecolonies.api.colony.IColony> getColoniesAbandonedSince(int);
  public abstract com.minecolonies.api.colony.buildings.views.IBuildingView getBuildingView(net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>, net.minecraft.core.BlockPos);
  public abstract java.util.List<com.minecolonies.api.colony.IColony> getIColonies(net.minecraft.world.level.Level);
  public abstract com.minecolonies.api.colony.IColony getIColony(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract java.util.List<com.minecolonies.api.colony.IColonyView> getColonyViews(net.minecraft.world.level.Level);
  public abstract com.minecolonies.api.colony.IColonyView getColonyView(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract com.minecolonies.api.colony.IColony getClosestIColony(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract com.minecolonies.api.colony.IColonyView getClosestColonyView(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract com.minecolonies.api.colony.IColony getClosestColony(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract com.minecolonies.api.colony.IColony getIColonyByOwner(net.minecraft.world.level.Level, net.minecraft.world.entity.player.Player);
  public abstract com.minecolonies.api.colony.IColony getIColonyByOwner(net.minecraft.world.level.Level, java.util.UUID);
  public abstract int getMinimumDistanceBetweenTownHalls();
  public abstract void onServerTick(net.neoforged.neoforge.event.tick.ServerTickEvent$Pre);
  public abstract void write(net.minecraft.core.HolderLookup$Provider, net.minecraft.nbt.CompoundTag);
  public abstract void read(net.minecraft.core.HolderLookup$Provider, net.minecraft.nbt.CompoundTag);
  public abstract void onClientTick(net.neoforged.neoforge.client.event.ClientTickEvent$Pre);
  public abstract void onWorldTick(net.neoforged.neoforge.event.tick.LevelTickEvent$Pre);
  public abstract void onWorldLoad(net.minecraft.world.level.Level);
  public abstract void onWorldUnload(net.minecraft.world.level.Level);
  public abstract void handleColonyViewMessage(int, net.minecraft.network.RegistryFriendlyByteBuf, boolean, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract com.minecolonies.api.colony.IColonyView getColonyView(int, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract void handlePermissionsViewMessage(int, net.minecraft.network.RegistryFriendlyByteBuf, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract void handleColonyViewCitizensMessage(int, int, net.minecraft.network.RegistryFriendlyByteBuf, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract void handleColonyViewWorkOrderMessage(int, net.minecraft.network.RegistryFriendlyByteBuf, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract void handleColonyViewRemoveCitizenMessage(int, int, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract void handleColonyBuildingViewMessage(int, net.minecraft.core.BlockPos, net.minecraft.network.RegistryFriendlyByteBuf, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract void handleColonyViewRemoveBuildingMessage(int, net.minecraft.core.BlockPos, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract void handleColonyViewRemoveWorkOrderMessage(int, int, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract boolean isSchematicDownloaded();
  public abstract void setSchematicDownloaded(boolean);
  public abstract boolean isCoordinateInAnyColony(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract com.minecolonies.api.compatibility.ICompatibilityManager getCompatibilityManager();
  public abstract com.minecolonies.api.crafting.IRecipeManager getRecipeManager();
  public abstract int getTopColonyId();
  public abstract void resetColonyViews();
  public abstract void openReactivationWindow(net.minecraft.core.BlockPos);
  public abstract void addColonyDirect(com.minecolonies.api.colony.IColony, net.minecraft.server.level.ServerLevel);
  public abstract void addClaimData(com.minecolonies.api.colony.IColony, it.unimi.dsi.fastutil.longs.Long2ObjectMap<com.minecolonies.api.colony.claim.ChunkClaimData>);
  public abstract java.util.Map<net.minecraft.world.level.ChunkPos, com.minecolonies.api.colony.claim.IChunkClaimData> getClaimData(net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public abstract com.minecolonies.api.colony.claim.IChunkClaimData getClaimData(net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>, net.minecraft.world.level.ChunkPos);
  public abstract void addNewChunk(com.minecolonies.core.colony.Colony, net.minecraft.world.level.ChunkPos, com.minecolonies.api.colony.claim.ChunkClaimData);
}
