Compiled from "IColonyView.java"
public interface com.minecolonies.api.colony.IColonyView extends com.minecolonies.api.colony.IColony {
  public abstract java.util.List<net.minecraft.core.BlockPos> getFreePositions();
  public abstract java.util.List<net.minecraft.world.level.block.Block> getFreeBlocks();
  public abstract void addFreePosition(net.minecraft.core.BlockPos);
  public abstract void addFreeBlock(net.minecraft.world.level.block.Block);
  public abstract void removeFreePosition(net.minecraft.core.BlockPos);
  public abstract void removeFreeBlock(net.minecraft.world.level.block.Block);
  public abstract net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level> getDimension();
  public abstract java.util.Map<java.util.UUID, com.minecolonies.api.colony.permissions.ColonyPlayer> getPlayers();
  public abstract int getCitizenCount();
  public abstract int getCitizenCountLimit();
  public abstract java.util.Map<java.lang.Integer, com.minecolonies.api.colony.ICitizenDataView> getCitizens();
  public abstract java.util.Collection<com.minecolonies.api.colony.workorders.IWorkOrderView> getWorkOrders();
  public abstract com.minecolonies.api.colony.workorders.IWorkOrderView getWorkOrder(int);
  public abstract com.minecolonies.api.colony.ICitizenDataView getCitizen(int);
  public abstract void handleColonyViewMessage(net.minecraft.network.RegistryFriendlyByteBuf, boolean);
  public abstract void handlePermissionsViewMessage(net.minecraft.network.RegistryFriendlyByteBuf);
  public abstract void handleColonyViewWorkOrderMessage(net.minecraft.network.RegistryFriendlyByteBuf);
  public abstract void handleColonyViewCitizensMessage(int, net.minecraft.network.RegistryFriendlyByteBuf);
  public abstract void handleColonyViewVisitorMessage(net.minecraft.network.RegistryFriendlyByteBuf, boolean);
  public abstract void handleColonyViewAnimalMessage(net.minecraft.network.RegistryFriendlyByteBuf, boolean);
  public abstract void handleColonyViewRemoveCitizenMessage(int);
  public abstract void handleColonyViewRemoveWorkOrderMessage(int);
  public abstract void handleColonyViewResearchManagerUpdate(net.minecraft.core.HolderLookup$Provider, net.minecraft.nbt.CompoundTag);
  public abstract void addPlayer(java.lang.String);
  public abstract void removePlayer(java.util.UUID);
  public abstract double getOverallHappiness();
  public abstract net.minecraft.core.BlockPos getCenter();
  public abstract java.lang.String getName();
  public abstract void setName(java.lang.String);
  public abstract com.minecolonies.api.colony.permissions.IPermissions getPermissions();
  public abstract boolean isCoordInColony(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract long getDistanceSquared(net.minecraft.core.BlockPos);
  public abstract int getID();
  public abstract int getLastContactInHours();
  public abstract net.minecraft.world.level.Level getWorld();
  public abstract com.minecolonies.api.colony.requestsystem.manager.IRequestManager getRequestManager();
  public abstract void markDirty();
  public abstract boolean canBeAutoDeleted();
  public abstract com.minecolonies.api.colony.requestsystem.requester.IRequester getRequesterBuildingForPosition(net.minecraft.core.BlockPos);
  public abstract void removeVisitingPlayer(net.minecraft.world.entity.player.Player);
  public abstract void addVisitingPlayer(net.minecraft.world.entity.player.Player);
  public abstract java.util.List<net.minecraft.core.BlockPos> getLastSpawnPoints();
  public abstract boolean isRemote();
  public abstract java.lang.String getStructurePack();
  public abstract boolean isRaiding();
  public abstract boolean areSpiesEnabled();
  public abstract com.minecolonies.api.colony.ICitizenDataView getVisitor(int);
  public abstract com.minecolonies.api.colony.managers.interfaces.IAnimalDataView getAnimal(int);
  public abstract java.util.List<java.lang.String> getNameFileIds();
  public abstract com.minecolonies.api.colony.managers.interfaces.views.IRegisteredStructureManagerView getClientBuildingManager();
  public default com.minecolonies.api.colony.ICitizen getCitizen(int);
}
