Compiled from "IColony.java"
public interface com.minecolonies.api.colony.IColony {
  public abstract void onWorldLoad(net.minecraft.server.level.ServerLevel);
  public abstract void onWorldUnload(net.minecraft.world.level.Level);
  public abstract void onServerTick(net.neoforged.neoforge.event.tick.ServerTickEvent$Pre);
  public abstract com.minecolonies.api.colony.workorders.IWorkManager getWorkManager();
  public abstract void onWorldTick(net.neoforged.neoforge.event.tick.LevelTickEvent$Pre);
  public abstract net.minecraft.core.BlockPos getCenter();
  public abstract java.lang.String getName();
  public abstract void setName(java.lang.String);
  public abstract com.minecolonies.api.colony.permissions.IPermissions getPermissions();
  public abstract boolean isCoordInColony(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public abstract long getDistanceSquared(net.minecraft.core.BlockPos);
  public abstract int getID();
  public abstract net.minecraft.ChatFormatting getTeamColonyColor();
  public abstract net.minecraft.world.level.block.entity.BannerPatternLayers getColonyFlag();
  public abstract boolean isDay();
  public abstract int getLastContactInHours();
  public abstract net.minecraft.world.level.Level getWorld();
  public abstract com.minecolonies.api.colony.requestsystem.manager.IRequestManager getRequestManager();
  public abstract void markDirty();
  public abstract boolean canBeAutoDeleted();
  public abstract com.minecolonies.api.colony.requestsystem.requester.IRequester getRequesterBuildingForPosition(net.minecraft.core.BlockPos);
  public abstract void removeVisitingPlayer(net.minecraft.world.entity.player.Player);
  public abstract java.util.List<net.minecraft.world.entity.player.Player> getMessagePlayerEntities();
  public default java.util.List<net.minecraft.core.BlockPos> getWayPoints(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public abstract double getOverallHappiness();
  public abstract java.util.Map<net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState> getWayPoints();
  public abstract java.lang.String getStructurePack();
  public abstract void setStructurePack(java.lang.String);
  public abstract com.minecolonies.api.colony.managers.interfaces.IRegisteredStructureManager getServerBuildingManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.ICommonRegisteredStructureManager getCommonBuildingManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.ICitizenManager getCitizenManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.IGraveManager getGraveManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.IVisitorManager getVisitorManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.IAnimalManager getAnimalManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.IRaiderManager getRaiderManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.IEventManager getEventManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.IReproductionManager getReproductionManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.IEventDescriptionManager getEventDescriptionManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.IColonyPackageManager getPackageManager();
  public abstract com.minecolonies.api.colony.managers.interfaces.ITravellingManager getTravellingManager();
  public abstract com.minecolonies.api.colony.connections.IColonyConnectionManager getConnectionManager();
  public abstract void addVisitingPlayer(net.minecraft.world.entity.player.Player);
  public abstract net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level> getDimension();
  public abstract boolean isRemote();
  public abstract com.minecolonies.api.research.IResearchManager getResearchManager();
  public abstract void usedMercenaries();
  public abstract long getMercenaryUseTime();
  public abstract net.minecraft.nbt.CompoundTag getColonyTag();
  public abstract boolean isColonyUnderAttack();
  public abstract boolean isValidAttackingPlayer(net.minecraft.world.entity.player.Player);
  public abstract boolean isValidAttackingGuard(com.minecolonies.api.entity.citizen.AbstractEntityCitizen);
  public abstract void setColonyColor(net.minecraft.ChatFormatting);
  public abstract void setColonyFlag(net.minecraft.world.level.block.entity.BannerPatternLayers);
  public abstract void addWayPoint(net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState);
  public abstract void addGuardToAttackers(com.minecolonies.api.entity.citizen.AbstractEntityCitizen, net.minecraft.world.entity.player.Player);
  public abstract void addFreePosition(net.minecraft.core.BlockPos);
  public abstract void addFreeBlock(net.minecraft.world.level.block.Block);
  public abstract void removeFreePosition(net.minecraft.core.BlockPos);
  public abstract void removeFreeBlock(net.minecraft.world.level.block.Block);
  public abstract void setCanBeAutoDeleted(boolean);
  public abstract net.minecraft.nbt.CompoundTag write(net.minecraft.nbt.CompoundTag, net.minecraft.core.HolderLookup$Provider);
  public abstract void read(net.minecraft.nbt.CompoundTag, net.minecraft.core.HolderLookup$Provider);
  public abstract java.util.List<net.minecraft.world.entity.player.Player> getImportantMessageEntityPlayers();
  public abstract boolean useAdditionalChildTime(int);
  public abstract void updateHasChilds();
  public abstract void addLoadedChunk(long, net.minecraft.world.level.chunk.LevelChunk);
  public abstract void removeLoadedChunk(long);
  public abstract int getLoadedChunkCount();
  public abstract java.util.Set<java.lang.Long> getLoadedChunks();
  public abstract com.minecolonies.api.colony.ColonyState getState();
  public abstract boolean isActive();
  public abstract java.util.Set<java.lang.Long> getTicketedChunks();
  public abstract void setTextureStyle(java.lang.String);
  public abstract java.lang.String getTextureStyleId();
  public abstract java.lang.String getNameStyle();
  public abstract void setNameStyle(java.lang.String);
  public abstract com.minecolonies.api.colony.CitizenNameFile getCitizenNameFile();
  public abstract com.minecolonies.api.colony.managers.interfaces.IStatisticsManager getStatisticsManager();
  public abstract int getDay();
  public abstract com.minecolonies.api.quests.IQuestManager getQuestManager();
  public abstract com.minecolonies.api.colony.ICitizen getCitizen(int);
  public abstract com.minecolonies.api.colony.buildings.modules.ICommonSettingsModule getSettings();
  public default void writeToItemStack(net.minecraft.world.item.ItemStack);
}
