Compiled from "IBuilding.java"
public interface com.minecolonies.api.colony.buildings.IBuilding extends com.minecolonies.api.colony.buildings.IBuildingContainer,com.minecolonies.api.colony.modules.IBuildingModuleContainer,com.minecolonies.api.colony.requestsystem.resolver.IRequestResolverProvider,com.minecolonies.api.colony.requestsystem.requester.IRequester,com.minecolonies.api.colony.buildings.ICommonBuilding {
  public static final int WOOD_HUT_LEVEL;
  public abstract java.lang.String getCustomName();
  public abstract java.lang.String getBuildingDisplayName();
  public default void onWakeUp();
  public abstract void onCleanUp(com.minecolonies.api.colony.ICitizenData);
  public abstract void onRestart(com.minecolonies.api.colony.ICitizenData);
  public abstract void onPlacement();
  public default void onPlayerEnterNearby(net.minecraft.world.entity.player.Player);
  public default void onPlayerEnterBuilding(net.minecraft.world.entity.player.Player);
  public abstract boolean isMatchingBlock(net.minecraft.world.level.block.Block);
  public abstract void destroy();
  public abstract void onDestroyed();
  public abstract boolean canBeBuiltByBuilder(int);
  public abstract void markDirty();
  public abstract boolean isPendingConstruction();
  public abstract void removeWorkOrder();
  public abstract int getClaimRadius(int);
  public abstract void serializeToView(net.minecraft.network.RegistryFriendlyByteBuf, boolean);
  public abstract void setCustomBuildingName(java.lang.String);
  public abstract boolean canBeGathered();
  public abstract void requestUpgrade(net.minecraft.world.entity.player.Player, net.minecraft.core.BlockPos);
  public abstract void requestRemoval(net.minecraft.world.entity.player.Player, net.minecraft.core.BlockPos);
  public abstract void requestRepair(net.minecraft.core.BlockPos);
  public abstract boolean isBuilt();
  public abstract void deconstruct();
  public abstract void onUpgradeComplete(com.ldtteam.structurize.blueprints.v1.Blueprint, int);
  public abstract boolean isGuardBuildingNear();
  public abstract void resetGuardBuildingNear();
  public abstract int buildingRequiresCertainAmountOfItem(net.minecraft.world.item.ItemStack, java.util.List<com.minecolonies.api.crafting.ItemStorage>, boolean, com.minecolonies.api.colony.jobs.registry.JobEntry);
  public default int buildingRequiresCertainAmountOfItem(net.minecraft.world.item.ItemStack, java.util.List<com.minecolonies.api.crafting.ItemStorage>, boolean);
  public abstract java.util.Map<java.util.function.Predicate<net.minecraft.world.item.ItemStack>, net.minecraft.util.Tuple<java.lang.Integer, java.lang.Boolean>> getRequiredItemsAndAmount();
  public abstract net.minecraft.world.item.ItemStack forceTransferStack(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level);
  public abstract <R extends com.minecolonies.api.colony.requestsystem.requestable.IRequestable> com.minecolonies.api.colony.requestsystem.token.IToken<?> createRequest(com.minecolonies.api.colony.ICitizenData, R, boolean);
  public abstract <R extends com.minecolonies.api.colony.requestsystem.requestable.IRequestable> com.minecolonies.api.colony.requestsystem.token.IToken<?> createRequest(R, boolean);
  public abstract boolean hasWorkerOpenRequests(int);
  public abstract java.util.Collection<com.minecolonies.api.colony.requestsystem.request.IRequest<?>> getOpenRequests(int);
  public abstract boolean hasWorkerOpenRequestsFiltered(int, java.util.function.Predicate<com.minecolonies.api.colony.requestsystem.request.IRequest<?>>);
  public abstract boolean hasOpenSyncRequest(com.minecolonies.api.colony.ICitizenData);
  public abstract <R> boolean hasWorkerOpenRequestsOfType(int, com.google.common.reflect.TypeToken<R>);
  public abstract <R> com.google.common.collect.ImmutableList<com.minecolonies.api.colony.requestsystem.request.IRequest<? extends R>> getOpenRequestsOfType(int, com.google.common.reflect.TypeToken<R>);
  public abstract boolean hasCitizenCompletedRequests(com.minecolonies.api.colony.ICitizenData);
  public abstract boolean hasCitizenCompletedRequestsToPickup(com.minecolonies.api.colony.ICitizenData);
  public abstract java.util.Collection<com.minecolonies.api.colony.requestsystem.request.IRequest<?>> getCompletedRequestsOfCitizenOrBuilding(com.minecolonies.api.colony.ICitizenData);
  public abstract <R> com.google.common.collect.ImmutableList<com.minecolonies.api.colony.requestsystem.request.IRequest<? extends R>> getCompletedRequestsOfType(com.minecolonies.api.colony.ICitizenData, com.google.common.reflect.TypeToken<R>);
  public abstract <R> com.google.common.collect.ImmutableList<com.minecolonies.api.colony.requestsystem.request.IRequest<? extends R>> getCompletedRequestsOfTypeFiltered(com.minecolonies.api.colony.ICitizenData, com.google.common.reflect.TypeToken<R>, java.util.function.Predicate<com.minecolonies.api.colony.requestsystem.request.IRequest<? extends R>>);
  public abstract void markRequestAsAccepted(com.minecolonies.api.colony.ICitizenData, com.minecolonies.api.colony.requestsystem.token.IToken<?>);
  public abstract void cancelAllRequestsOfCitizenOrBuilding(com.minecolonies.api.colony.ICitizenData);
  public abstract void overruleNextOpenRequestWithStack(net.minecraft.world.item.ItemStack);
  public abstract <R> com.google.common.collect.ImmutableList<com.minecolonies.api.colony.requestsystem.request.IRequest<? extends R>> getOpenRequestsOfTypeFiltered(com.minecolonies.api.colony.ICitizenData, com.google.common.reflect.TypeToken<R>, java.util.function.Predicate<com.minecolonies.api.colony.requestsystem.request.IRequest<? extends R>>);
  public abstract boolean overruleNextOpenRequestOfCitizenWithStack(com.minecolonies.api.colony.ICitizenData, net.minecraft.world.item.ItemStack);
  public abstract boolean createPickupRequest(int);
  public abstract com.google.common.collect.ImmutableCollection<com.minecolonies.api.colony.requestsystem.resolver.IRequestResolver<?>> getResolvers();
  public abstract com.google.common.collect.ImmutableCollection<com.minecolonies.api.colony.requestsystem.resolver.IRequestResolver<?>> createResolvers();
  public abstract com.minecolonies.api.colony.requestsystem.requester.IRequester getRequester();
  public abstract java.util.Optional<com.minecolonies.api.colony.ICitizenData> getCitizenForRequest(com.minecolonies.api.colony.requestsystem.token.IToken<?>);
  public abstract java.util.Map<com.minecolonies.api.crafting.ItemStorage, java.lang.Integer> reservedStacksExcluding(com.minecolonies.api.colony.requestsystem.request.IRequest<? extends com.minecolonies.api.colony.requestsystem.requestable.IDeliverable>);
  public abstract void processOfflineTime(long);
  public abstract void calculateCorners();
  public abstract boolean isInBuilding(net.minecraft.core.BlockPos);
  public abstract void upgradeBuildingLevelToSchematicData();
  public abstract java.util.Map<com.google.common.reflect.TypeToken<?>, java.util.Collection<com.minecolonies.api.colony.requestsystem.token.IToken<?>>> getOpenRequestsByRequestableType();
  public abstract void pickUp(net.minecraft.world.entity.player.Player);
  public abstract void setBuildingType(com.minecolonies.api.colony.buildings.registry.BuildingEntry);
  public abstract void onColonyTick(com.minecolonies.api.colony.IColony);
  public abstract boolean isItemStackInRequest(net.minecraft.world.item.ItemStack);
  public default int getMaxEquipmentLevel();
  public default boolean canAssignCitizens();
  public abstract java.util.Set<com.minecolonies.api.colony.ICitizenData> getAllAssignedCitizen();
  public abstract java.util.List<net.neoforged.neoforge.items.IItemHandler> getHandlers();
  public abstract <T extends com.minecolonies.api.colony.buildings.modules.settings.ISetting<S>, S> T getSetting(com.minecolonies.api.colony.buildings.modules.settings.ISettingKey<T>);
  public abstract <T extends com.minecolonies.api.colony.buildings.modules.settings.ISetting<S>, S> S getSettingValueOrDefault(com.minecolonies.api.colony.buildings.modules.settings.ISettingKey<T>, S);
  public default boolean canEat(net.minecraft.world.item.ItemStack);
  public default void writeToItemStack(net.minecraft.world.item.ItemStack);
  public abstract java.util.List<net.minecraft.core.BlockPos> getLocationsFromTag(java.lang.String);
  public default boolean canSort();
  public default void sort(net.minecraft.core.HolderLookup$Provider, com.minecolonies.api.inventory.api.CombinedItemHandler);
  public abstract void calculatePrestige(com.ldtteam.structurize.blueprints.v1.Blueprint);
  public abstract void asyncPrestigeRecalc();
}
