Compiled from "PayloadRegistrar.java"
public class net.neoforged.neoforge.network.registration.PayloadRegistrar {
  public net.neoforged.neoforge.network.registration.PayloadRegistrar(java.lang.String);
  public <T extends net.minecraft.network.protocol.common.custom.CustomPacketPayload> net.neoforged.neoforge.network.registration.PayloadRegistrar playToClient(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type<T>, net.minecraft.network.codec.StreamCodec<? super net.minecraft.network.RegistryFriendlyByteBuf, T>, net.neoforged.neoforge.network.handling.IPayloadHandler<T>);
  public <T extends net.minecraft.network.protocol.common.custom.CustomPacketPayload> net.neoforged.neoforge.network.registration.PayloadRegistrar playToServer(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type<T>, net.minecraft.network.codec.StreamCodec<? super net.minecraft.network.RegistryFriendlyByteBuf, T>, net.neoforged.neoforge.network.handling.IPayloadHandler<T>);
  public <T extends net.minecraft.network.protocol.common.custom.CustomPacketPayload> net.neoforged.neoforge.network.registration.PayloadRegistrar playBidirectional(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type<T>, net.minecraft.network.codec.StreamCodec<? super net.minecraft.network.RegistryFriendlyByteBuf, T>, net.neoforged.neoforge.network.handling.IPayloadHandler<T>);
  public <T extends net.minecraft.network.protocol.common.custom.CustomPacketPayload> net.neoforged.neoforge.network.registration.PayloadRegistrar configurationToClient(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type<T>, net.minecraft.network.codec.StreamCodec<? super net.minecraft.network.FriendlyByteBuf, T>, net.neoforged.neoforge.network.handling.IPayloadHandler<T>);
  public <T extends net.minecraft.network.protocol.common.custom.CustomPacketPayload> net.neoforged.neoforge.network.registration.PayloadRegistrar configurationToServer(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type<T>, net.minecraft.network.codec.StreamCodec<? super net.minecraft.network.FriendlyByteBuf, T>, net.neoforged.neoforge.network.handling.IPayloadHandler<T>);
  public <T extends net.minecraft.network.protocol.common.custom.CustomPacketPayload> net.neoforged.neoforge.network.registration.PayloadRegistrar configurationBidirectional(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type<T>, net.minecraft.network.codec.StreamCodec<? super net.minecraft.network.FriendlyByteBuf, T>, net.neoforged.neoforge.network.handling.IPayloadHandler<T>);
  public <T extends net.minecraft.network.protocol.common.custom.CustomPacketPayload> net.neoforged.neoforge.network.registration.PayloadRegistrar commonToClient(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type<T>, net.minecraft.network.codec.StreamCodec<? super net.minecraft.network.FriendlyByteBuf, T>, net.neoforged.neoforge.network.handling.IPayloadHandler<T>);
  public <T extends net.minecraft.network.protocol.common.custom.CustomPacketPayload> net.neoforged.neoforge.network.registration.PayloadRegistrar commonToServer(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type<T>, net.minecraft.network.codec.StreamCodec<? super net.minecraft.network.FriendlyByteBuf, T>, net.neoforged.neoforge.network.handling.IPayloadHandler<T>);
  public <T extends net.minecraft.network.protocol.common.custom.CustomPacketPayload> net.neoforged.neoforge.network.registration.PayloadRegistrar commonBidirectional(net.minecraft.network.protocol.common.custom.CustomPacketPayload$Type<T>, net.minecraft.network.codec.StreamCodec<? super net.minecraft.network.FriendlyByteBuf, T>, net.neoforged.neoforge.network.handling.IPayloadHandler<T>);
  public net.neoforged.neoforge.network.registration.PayloadRegistrar executesOn(net.neoforged.neoforge.network.registration.HandlerThread);
  public net.neoforged.neoforge.network.registration.PayloadRegistrar versioned(java.lang.String);
  public net.neoforged.neoforge.network.registration.PayloadRegistrar optional();
}
