Compiled from "SchematicTagConstants.java"
public class com.minecolonies.api.util.constant.SchematicTagConstants {
  public static final java.lang.String TAG_SITTING;
  public static final java.lang.String TAG_WORK;
  public static final java.lang.String TAG_SIT_IN;
  public static final java.lang.String TAG_SIT_OUT;
  public static final java.lang.String TAG_STAND_IN;
  public static final java.lang.String TAG_STAND_OUT;
  public static final java.lang.String BUILDING_SIGN;
  public static final java.lang.String TAG_GROUNDLEVEL;
  public static final java.lang.String TAG_KNIGHT;
  public static final java.lang.String TAG_ARCHER;
  public static final java.lang.String TAG_GATE;
  public static final java.lang.String TAG_PATROL_POINT;
  public static final java.lang.String NORMAL_RAIDER;
  public static final java.lang.String ARCHER_RAIDER;
  public static final java.lang.String BOSS_RAIDER;
  public static final java.lang.String TAG_COBBLE;
  public static final java.lang.String TAG_LADDER;
  public static final java.lang.String TAG_LEISURE;
  public static final java.lang.String SUGAR_FIELD;
  public static final java.lang.String SUGAR_CROP;
  public static final java.lang.String CACTUS_FIELD;
  public static final java.lang.String CACTUS_CROP;
  public static final java.lang.String BAMBOO_FIELD;
  public static final java.lang.String BAMBOO_CROP;
  public static final java.lang.String COCOA_FIELD;
  public static final java.lang.String COCOA_CROP;
  public static final java.lang.String VINE_FIELD;
  public static final java.lang.String VINE_CROP;
  public static final java.lang.String KELP_FIELD;
  public static final java.lang.String KELP_CROP;
  public static final java.lang.String SEA_GRASS_FIELD;
  public static final java.lang.String SEA_GRASS_CROP;
  public static final java.lang.String SEA_PICKLE_FIELD;
  public static final java.lang.String SEA_PICKLE_CROP;
  public static final java.lang.String GLOW_BERRY_FIELD;
  public static final java.lang.String GLOW_BERRY_CROP;
  public static final java.lang.String WEEPY_VINE_FIELD;
  public static final java.lang.String WEEPY_VINE_CROP;
  public static final java.lang.String TWISTY_VINE_FIELD;
  public static final java.lang.String TWISTY_VINE_CROP;
  public static final java.lang.String CRIMSON_FIELD;
  public static final java.lang.String CRIMSON_CROP;
  public static final java.lang.String WARPED_FIELD;
  public static final java.lang.String WARPED_CROP;
  public com.minecolonies.api.util.constant.SchematicTagConstants();
  public static java.lang.String[] getPlantationTags();
}
