Compiled from "ModEntities.java"
public class com.minecolonies.api.entity.ModEntities {
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.citizen.AbstractEntityCitizen> CITIZEN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.citizen.AbstractEntityCitizen> VISITOR;
  public static net.minecraft.world.entity.EntityType<com.minecolonies.core.entity.other.NewBobberEntity> FISHHOOK;
  public static net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.PathfinderMob> MERCENARY;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.barbarians.AbstractEntityBarbarianRaider> BARBARIAN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.barbarians.AbstractEntityBarbarianRaider> ARCHERBARBARIAN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.barbarians.AbstractEntityBarbarianRaider> CHIEFBARBARIAN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.pirates.AbstractEntityPirateRaider> PIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.pirates.AbstractEntityPirateRaider> CHIEFPIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.pirates.AbstractEntityPirateRaider> ARCHERPIRATE;
  public static net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.Entity> SITTINGENTITY;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.egyptians.AbstractEntityEgyptianRaider> MUMMY;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.egyptians.AbstractEntityEgyptianRaider> PHARAO;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.egyptians.AbstractEntityEgyptianRaider> ARCHERMUMMY;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.vikings.AbstractEntityNorsemenRaider> NORSEMEN_ARCHER;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.vikings.AbstractEntityNorsemenRaider> SHIELDMAIDEN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.vikings.AbstractEntityNorsemenRaider> NORSEMEN_CHIEF;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.amazons.AbstractEntityAmazonRaider> AMAZON;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.amazons.AbstractEntityAmazonRaider> AMAZONSPEARMAN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.amazons.AbstractEntityAmazonRaider> AMAZONCHIEF;
  public static net.minecraft.world.entity.EntityType<com.minecolonies.api.entity.other.MinecoloniesMinecart> MINECART;
  public static net.minecraft.world.entity.EntityType<com.minecolonies.core.entity.other.cavalry.CavalryHorseEntity> CAVALRY_HORSE;
  public static net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.projectile.AbstractArrow> FIREARROW;
  public static net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.projectile.Arrow> MC_NORMAL_ARROW;
  public static net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.projectile.ThrownPotion> DRUID_POTION;
  public static net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.projectile.ThrownTrident> SPEAR;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.drownedpirate.AbstractDrownedEntityPirateRaider> DROWNED_PIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.drownedpirate.AbstractDrownedEntityPirateRaider> DROWNED_CHIEFPIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.drownedpirate.AbstractDrownedEntityPirateRaider> DROWNED_ARCHERPIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.barbarians.AbstractEntityBarbarian> CAMP_BARBARIAN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.barbarians.AbstractEntityBarbarian> CAMP_ARCHERBARBARIAN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.barbarians.AbstractEntityBarbarian> CAMP_CHIEFBARBARIAN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.pirates.AbstractEntityPirate> CAMP_PIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.pirates.AbstractEntityPirate> CAMP_CHIEFPIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.pirates.AbstractEntityPirate> CAMP_ARCHERPIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.amazons.AbstractEntityAmazon> CAMP_AMAZON;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.amazons.AbstractEntityAmazon> CAMP_AMAZONSPEARMAN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.amazons.AbstractEntityAmazon> CAMP_AMAZONCHIEF;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.egyptians.AbstractEntityEgyptian> CAMP_MUMMY;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.egyptians.AbstractEntityEgyptian> CAMP_PHARAO;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.egyptians.AbstractEntityEgyptian> CAMP_ARCHERMUMMY;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.vikings.AbstractEntityNorsemen> CAMP_NORSEMEN_ARCHER;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.vikings.AbstractEntityNorsemen> CAMP_SHIELDMAIDEN;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.vikings.AbstractEntityNorsemen> CAMP_NORSEMEN_CHIEF;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.drownedpirate.AbstractDrownedEntityPirate> CAMP_DROWNED_PIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.drownedpirate.AbstractDrownedEntityPirate> CAMP_DROWNED_CHIEFPIRATE;
  public static net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.drownedpirate.AbstractDrownedEntityPirate> CAMP_DROWNED_ARCHERPIRATE;
  public com.minecolonies.api.entity.ModEntities();
  public static java.util.List<net.minecraft.world.entity.EntityType<? extends com.minecolonies.api.entity.mobs.AbstractEntityMinecoloniesRaider>> getRaiders();
}
