Compiled from "FluidStack.java"
public final class net.neoforged.neoforge.fluids.FluidStack implements net.neoforged.neoforge.common.MutableDataComponentHolder {
  public static final com.mojang.serialization.Codec<net.minecraft.core.Holder<net.minecraft.world.level.material.Fluid>> FLUID_NON_EMPTY_CODEC;
  public static final com.mojang.serialization.Codec<net.neoforged.neoforge.fluids.FluidStack> CODEC;
  public static final com.mojang.serialization.Codec<net.neoforged.neoforge.fluids.FluidStack> OPTIONAL_CODEC;
  public static final net.minecraft.network.codec.StreamCodec<net.minecraft.network.RegistryFriendlyByteBuf, net.neoforged.neoforge.fluids.FluidStack> OPTIONAL_STREAM_CODEC;
  public static final net.minecraft.network.codec.StreamCodec<net.minecraft.network.RegistryFriendlyByteBuf, net.neoforged.neoforge.fluids.FluidStack> STREAM_CODEC;
  public static final net.neoforged.neoforge.fluids.FluidStack EMPTY;
  public static com.mojang.serialization.Codec<net.neoforged.neoforge.fluids.FluidStack> fixedAmountCodec(int);
  public net.minecraft.core.component.PatchedDataComponentMap getComponents();
  public net.minecraft.core.component.DataComponentPatch getComponentsPatch();
  public boolean isComponentsPatchEmpty();
  public net.neoforged.neoforge.fluids.FluidStack(net.minecraft.core.Holder<net.minecraft.world.level.material.Fluid>, int, net.minecraft.core.component.DataComponentPatch);
  public net.neoforged.neoforge.fluids.FluidStack(net.minecraft.core.Holder<net.minecraft.world.level.material.Fluid>, int);
  public net.neoforged.neoforge.fluids.FluidStack(net.minecraft.world.level.material.Fluid, int);
  public static java.util.Optional<net.neoforged.neoforge.fluids.FluidStack> parse(net.minecraft.core.HolderLookup$Provider, net.minecraft.nbt.Tag);
  public static net.neoforged.neoforge.fluids.FluidStack parseOptional(net.minecraft.core.HolderLookup$Provider, net.minecraft.nbt.CompoundTag);
  public boolean isEmpty();
  public net.neoforged.neoforge.fluids.FluidStack split(int);
  public net.neoforged.neoforge.fluids.FluidStack copyAndClear();
  public net.minecraft.world.level.material.Fluid getFluid();
  public net.minecraft.core.Holder<net.minecraft.world.level.material.Fluid> getFluidHolder();
  public boolean is(net.minecraft.tags.TagKey<net.minecraft.world.level.material.Fluid>);
  public boolean is(net.minecraft.world.level.material.Fluid);
  public boolean is(java.util.function.Predicate<net.minecraft.core.Holder<net.minecraft.world.level.material.Fluid>>);
  public boolean is(net.minecraft.core.Holder<net.minecraft.world.level.material.Fluid>);
  public boolean is(net.minecraft.core.HolderSet<net.minecraft.world.level.material.Fluid>);
  public java.util.stream.Stream<net.minecraft.tags.TagKey<net.minecraft.world.level.material.Fluid>> getTags();
  public net.minecraft.nbt.Tag save(net.minecraft.core.HolderLookup$Provider, net.minecraft.nbt.Tag);
  public net.minecraft.nbt.Tag save(net.minecraft.core.HolderLookup$Provider);
  public net.minecraft.nbt.Tag saveOptional(net.minecraft.core.HolderLookup$Provider);
  public net.neoforged.neoforge.fluids.FluidStack copy();
  public net.neoforged.neoforge.fluids.FluidStack copyWithAmount(int);
  public static boolean matches(net.neoforged.neoforge.fluids.FluidStack, net.neoforged.neoforge.fluids.FluidStack);
  public static boolean isSameFluid(net.neoforged.neoforge.fluids.FluidStack, net.neoforged.neoforge.fluids.FluidStack);
  public static boolean isSameFluidSameComponents(net.neoforged.neoforge.fluids.FluidStack, net.neoforged.neoforge.fluids.FluidStack);
  public static com.mojang.serialization.MapCodec<net.neoforged.neoforge.fluids.FluidStack> lenientOtionalFieldOf(java.lang.String);
  public static int hashFluidAndComponents(net.neoforged.neoforge.fluids.FluidStack);
  public java.lang.String getDescriptionId();
  public java.lang.String toString();
  public <T> T set(net.minecraft.core.component.DataComponentType<? super T>, T);
  public <T> T remove(net.minecraft.core.component.DataComponentType<? extends T>);
  public void applyComponents(net.minecraft.core.component.DataComponentPatch);
  public void applyComponents(net.minecraft.core.component.DataComponentMap);
  public net.minecraft.network.chat.Component getHoverName();
  public int getAmount();
  public void setAmount(int);
  public void limitSize(int);
  public void grow(int);
  public void shrink(int);
  public net.neoforged.neoforge.fluids.FluidType getFluidType();
  public boolean is(net.neoforged.neoforge.fluids.FluidType);
  public net.minecraft.network.chat.Component getDisplayName();
  public java.lang.String getTranslationKey();
  public boolean isFluidEqual(net.neoforged.neoforge.fluids.FluidStack);
  public static boolean areFluidStackTagsEqual(net.neoforged.neoforge.fluids.FluidStack, net.neoforged.neoforge.fluids.FluidStack);
  public boolean containsFluid(net.neoforged.neoforge.fluids.FluidStack);
  public boolean isFluidStackIdentical(net.neoforged.neoforge.fluids.FluidStack);
  public boolean isFluidEqual(net.minecraft.world.item.ItemStack);
  public net.minecraft.core.component.DataComponentMap getComponents();
}
