Compiled from "FluidType.java"
public class net.neoforged.neoforge.fluids.FluidType {
  public static final int BUCKET_VOLUME;
  public static final net.neoforged.neoforge.common.util.Lazy<java.lang.Integer> SIZE;
  public net.neoforged.neoforge.fluids.FluidType(net.neoforged.neoforge.fluids.FluidType$Properties);
  public net.minecraft.network.chat.Component getDescription();
  public java.lang.String getDescriptionId();
  public int getLightLevel();
  public int getDensity();
  public int getTemperature();
  public int getViscosity();
  public net.minecraft.world.item.Rarity getRarity();
  public net.neoforged.neoforge.fluids.FluidType$DripstoneDripInfo getDripInfo();
  public net.minecraft.sounds.SoundEvent getSound(net.neoforged.neoforge.common.SoundAction);
  public double motionScale(net.minecraft.world.entity.Entity);
  public boolean canPushEntity(net.minecraft.world.entity.Entity);
  public boolean canSwim(net.minecraft.world.entity.Entity);
  public float getFallDistanceModifier(net.minecraft.world.entity.Entity);
  public boolean canExtinguish(net.minecraft.world.entity.Entity);
  public boolean move(net.minecraft.world.level.material.FluidState, net.minecraft.world.entity.LivingEntity, net.minecraft.world.phys.Vec3, double);
  public boolean canDrownIn(net.minecraft.world.entity.LivingEntity);
  public void setItemMovement(net.minecraft.world.entity.item.ItemEntity);
  public boolean supportsBoating(net.minecraft.world.entity.vehicle.Boat);
  public boolean supportsBoating(net.minecraft.world.level.material.FluidState, net.minecraft.world.entity.vehicle.Boat);
  public boolean canRideVehicleUnder(net.minecraft.world.entity.Entity, net.minecraft.world.entity.Entity);
  public boolean canHydrate(net.minecraft.world.entity.Entity);
  public net.minecraft.sounds.SoundEvent getSound(net.minecraft.world.entity.Entity, net.neoforged.neoforge.common.SoundAction);
  public boolean canExtinguish(net.minecraft.world.level.material.FluidState, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos);
  public boolean canConvertToSource(net.minecraft.world.level.material.FluidState, net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos);
  public net.minecraft.world.level.pathfinder.PathType getBlockPathType(net.minecraft.world.level.material.FluidState, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.entity.Mob, boolean);
  public net.minecraft.world.level.pathfinder.PathType getAdjacentBlockPathType(net.minecraft.world.level.material.FluidState, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.entity.Mob, net.minecraft.world.level.pathfinder.PathType);
  public net.minecraft.sounds.SoundEvent getSound(net.minecraft.world.entity.player.Player, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.neoforged.neoforge.common.SoundAction);
  public boolean canHydrate(net.minecraft.world.level.material.FluidState, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.core.BlockPos);
  public int getLightLevel(net.minecraft.world.level.material.FluidState, net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos);
  public int getDensity(net.minecraft.world.level.material.FluidState, net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos);
  public int getTemperature(net.minecraft.world.level.material.FluidState, net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos);
  public int getViscosity(net.minecraft.world.level.material.FluidState, net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos);
  public boolean handleCauldronDrip(net.minecraft.world.level.material.Fluid, net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public boolean canConvertToSource(net.neoforged.neoforge.fluids.FluidStack);
  public net.minecraft.sounds.SoundEvent getSound(net.neoforged.neoforge.fluids.FluidStack, net.neoforged.neoforge.common.SoundAction);
  public net.minecraft.network.chat.Component getDescription(net.neoforged.neoforge.fluids.FluidStack);
  public java.lang.String getDescriptionId(net.neoforged.neoforge.fluids.FluidStack);
  public boolean canHydrate(net.neoforged.neoforge.fluids.FluidStack);
  public int getLightLevel(net.neoforged.neoforge.fluids.FluidStack);
  public int getDensity(net.neoforged.neoforge.fluids.FluidStack);
  public int getTemperature(net.neoforged.neoforge.fluids.FluidStack);
  public int getViscosity(net.neoforged.neoforge.fluids.FluidStack);
  public net.minecraft.world.item.Rarity getRarity(net.neoforged.neoforge.fluids.FluidStack);
  public final boolean isAir();
  public final boolean isVanilla();
  public net.minecraft.world.item.ItemStack getBucket(net.neoforged.neoforge.fluids.FluidStack);
  public net.minecraft.world.level.block.state.BlockState getBlockForFluidState(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos, net.minecraft.world.level.material.FluidState);
  public net.minecraft.world.level.material.FluidState getStateForPlacement(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos, net.neoforged.neoforge.fluids.FluidStack);
  public final boolean canBePlacedInLevel(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos, net.minecraft.world.level.material.FluidState);
  public final boolean canBePlacedInLevel(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos, net.neoforged.neoforge.fluids.FluidStack);
  public final boolean isLighterThanAir();
  public boolean isVaporizedOnPlacement(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.neoforged.neoforge.fluids.FluidStack);
  public void onVaporize(net.minecraft.world.entity.player.Player, net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.neoforged.neoforge.fluids.FluidStack);
  public java.lang.String toString();
  public void initializeClient(java.util.function.Consumer<net.neoforged.neoforge.client.extensions.common.IClientFluidTypeExtensions>);
}
