Compiled from "CommonHooks.java"
public class net.neoforged.neoforge.common.CommonHooks {
  public static final int VANILLA_SERIALIZER_LIMIT;
  public net.neoforged.neoforge.common.CommonHooks();
  public static boolean canContinueUsing(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack);
  public static boolean onItemStackedOn(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, net.minecraft.world.inventory.Slot, net.minecraft.world.inventory.ClickAction, net.minecraft.world.entity.player.Player, net.minecraft.world.entity.SlotAccess);
  public static void onDifficultyChange(net.minecraft.world.Difficulty, net.minecraft.world.Difficulty);
  public static net.neoforged.neoforge.event.entity.living.LivingChangeTargetEvent onLivingChangeTarget(net.minecraft.world.entity.LivingEntity, net.minecraft.world.entity.LivingEntity, net.neoforged.neoforge.event.entity.living.LivingChangeTargetEvent$ILivingTargetType);
  public static boolean isEntityInvulnerableTo(net.minecraft.world.entity.Entity, net.minecraft.world.damagesource.DamageSource, boolean);
  public static boolean onEntityIncomingDamage(net.minecraft.world.entity.LivingEntity, net.neoforged.neoforge.common.damagesource.DamageContainer);
  public static net.neoforged.neoforge.event.entity.living.LivingKnockBackEvent onLivingKnockBack(net.minecraft.world.entity.LivingEntity, float, double, double);
  public static boolean onLivingUseTotem(net.minecraft.world.entity.LivingEntity, net.minecraft.world.damagesource.DamageSource, net.minecraft.world.item.ItemStack, net.minecraft.world.InteractionHand);
  public static float onLivingDamagePre(net.minecraft.world.entity.LivingEntity, net.neoforged.neoforge.common.damagesource.DamageContainer);
  public static void onLivingDamagePost(net.minecraft.world.entity.LivingEntity, net.neoforged.neoforge.common.damagesource.DamageContainer);
  public static void onArmorHurt(net.minecraft.world.damagesource.DamageSource, net.minecraft.world.entity.EquipmentSlot[], float, net.minecraft.world.entity.LivingEntity);
  public static boolean onLivingDeath(net.minecraft.world.entity.LivingEntity, net.minecraft.world.damagesource.DamageSource);
  public static boolean onLivingDrops(net.minecraft.world.entity.LivingEntity, net.minecraft.world.damagesource.DamageSource, java.util.Collection<net.minecraft.world.entity.item.ItemEntity>, boolean);
  public static float[] onLivingFall(net.minecraft.world.entity.LivingEntity, float, float);
  public static double getEntityVisibilityMultiplier(net.minecraft.world.entity.LivingEntity, net.minecraft.world.entity.Entity, double);
  public static java.util.Optional<net.minecraft.core.BlockPos> isLivingOnLadder(net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.entity.LivingEntity);
  public static void onLivingJump(net.minecraft.world.entity.LivingEntity);
  public static net.minecraft.world.entity.item.ItemEntity onPlayerTossEvent(net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack, boolean);
  public static boolean onVanillaGameEvent(net.minecraft.world.level.Level, net.minecraft.core.Holder<net.minecraft.world.level.gameevent.GameEvent>, net.minecraft.world.phys.Vec3, net.minecraft.world.level.gameevent.GameEvent$Context);
  public static net.minecraft.network.chat.Component onServerChatSubmittedEvent(net.minecraft.server.level.ServerPlayer, java.lang.String, net.minecraft.network.chat.Component);
  public static net.minecraft.network.chat.ChatDecorator getServerChatSubmittedDecorator();
  public static net.minecraft.network.chat.Component newChatWithLinks(java.lang.String);
  public static net.minecraft.network.chat.Component newChatWithLinks(java.lang.String, boolean);
  public static void handleBlockDrops(net.minecraft.server.level.ServerLevel, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.block.entity.BlockEntity, java.util.List<net.minecraft.world.entity.item.ItemEntity>, net.minecraft.world.entity.Entity, net.minecraft.world.item.ItemStack);
  public static net.neoforged.neoforge.event.level.BlockEvent$BreakEvent fireBlockBreak(net.minecraft.world.level.Level, net.minecraft.world.level.GameType, net.minecraft.server.level.ServerPlayer, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState);
  public static net.minecraft.world.InteractionResult onPlaceItemIntoWorld(net.minecraft.world.item.context.UseOnContext);
  public static void onPlayerEnchantItem(net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack, java.util.List<net.minecraft.world.item.enchantment.EnchantmentInstance>);
  public static boolean onAnvilChange(net.minecraft.world.inventory.AnvilMenu, net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, net.minecraft.world.Container, java.lang.String, long, net.minecraft.world.entity.player.Player);
  public static float onAnvilRepair(net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack);
  public static int onGrindstoneChange(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, net.minecraft.world.Container, int);
  public static boolean onGrindstoneTake(net.minecraft.world.Container, net.minecraft.world.inventory.ContainerLevelAccess, java.util.function.Function<net.minecraft.world.level.Level, java.lang.Integer>);
  public static boolean onGrindstoneTake(net.minecraft.world.Container, net.minecraft.world.inventory.ContainerLevelAccess, net.minecraft.world.entity.player.Player, java.util.function.Function<net.minecraft.world.level.Level, java.lang.Integer>);
  public static void setCraftingPlayer(net.minecraft.world.entity.player.Player);
  public static net.minecraft.world.entity.player.Player getCraftingPlayer();
  public static net.minecraft.world.item.ItemStack getCraftingRemainingItem(net.minecraft.world.item.ItemStack);
  public static boolean onPlayerAttackTarget(net.minecraft.world.entity.player.Player, net.minecraft.world.entity.Entity);
  public static boolean onTravelToDimension(net.minecraft.world.entity.Entity, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public static net.minecraft.world.InteractionResult onInteractEntityAt(net.minecraft.world.entity.player.Player, net.minecraft.world.entity.Entity, net.minecraft.world.phys.HitResult, net.minecraft.world.InteractionHand);
  public static net.minecraft.world.InteractionResult onInteractEntityAt(net.minecraft.world.entity.player.Player, net.minecraft.world.entity.Entity, net.minecraft.world.phys.Vec3, net.minecraft.world.InteractionHand);
  public static net.minecraft.world.InteractionResult onInteractEntity(net.minecraft.world.entity.player.Player, net.minecraft.world.entity.Entity, net.minecraft.world.InteractionHand);
  public static net.minecraft.world.InteractionResult onItemRightClick(net.minecraft.world.entity.player.Player, net.minecraft.world.InteractionHand);
  public static net.neoforged.neoforge.event.entity.player.PlayerInteractEvent$LeftClickBlock onLeftClickBlock(net.minecraft.world.entity.player.Player, net.minecraft.core.BlockPos, net.minecraft.core.Direction, net.minecraft.network.protocol.game.ServerboundPlayerActionPacket$Action);
  public static net.neoforged.neoforge.event.entity.player.PlayerInteractEvent$LeftClickBlock onClientMineHold(net.minecraft.world.entity.player.Player, net.minecraft.core.BlockPos, net.minecraft.core.Direction);
  public static net.neoforged.neoforge.event.entity.player.PlayerInteractEvent$RightClickBlock onRightClickBlock(net.minecraft.world.entity.player.Player, net.minecraft.world.InteractionHand, net.minecraft.core.BlockPos, net.minecraft.world.phys.BlockHitResult);
  public static void onEmptyClick(net.minecraft.world.entity.player.Player, net.minecraft.world.InteractionHand);
  public static void onEmptyLeftClick(net.minecraft.world.entity.player.Player);
  public static net.minecraft.world.level.GameType onChangeGameType(net.minecraft.world.entity.player.Player, net.minecraft.world.level.GameType, net.minecraft.world.level.GameType);
  public static com.mojang.serialization.Codec<java.util.List<net.minecraft.world.level.storage.loot.LootPool>> lootPoolsCodec(java.util.function.BiConsumer<net.minecraft.world.level.storage.loot.LootPool, java.lang.String>);
  public static net.neoforged.neoforge.fluids.FluidType getVanillaFluidType(net.minecraft.world.level.material.Fluid);
  public static net.minecraft.tags.TagKey<net.minecraft.world.level.block.Block> getTagFromVanillaTier(net.minecraft.world.item.Tiers);
  public static java.util.Collection<net.minecraft.world.item.CreativeModeTab> onCheckCreativeTabs(net.minecraft.world.item.CreativeModeTab...);
  public static boolean canCropGrow(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, boolean);
  public static void fireCropGrowPost(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState);
  public static net.neoforged.neoforge.event.entity.player.CriticalHitEvent fireCriticalHit(net.minecraft.world.entity.player.Player, net.minecraft.world.entity.Entity, boolean, float);
  public static net.neoforged.neoforge.event.entity.player.SweepAttackEvent fireSweepAttack(net.minecraft.world.entity.player.Player, net.minecraft.world.entity.Entity, boolean);
  public static net.minecraft.world.item.component.ItemAttributeModifiers computeModifiedAttributes(net.minecraft.world.item.ItemStack, net.minecraft.world.item.component.ItemAttributeModifiers);
  public static net.minecraft.world.item.ItemStack getProjectile(net.minecraft.world.entity.LivingEntity, net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack);
  public static java.lang.String getDefaultCreatorModId(net.minecraft.world.item.ItemStack);
  public static boolean onFarmlandTrample(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, float, net.minecraft.world.entity.Entity);
  public static int onNoteChange(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, int, int);
  public static net.minecraft.network.syncher.EntityDataSerializer<?> getSerializer(int, net.minecraft.util.CrudeIncrementalIntIdentityHashBiMap<net.minecraft.network.syncher.EntityDataSerializer<?>>);
  public static int getSerializerId(net.minecraft.network.syncher.EntityDataSerializer<?>, net.minecraft.util.CrudeIncrementalIntIdentityHashBiMap<net.minecraft.network.syncher.EntityDataSerializer<?>>);
  public static boolean canEntityDestroy(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.entity.LivingEntity);
  public static java.util.List<net.minecraft.world.item.ItemStack> modifyLoot(java.util.List<net.minecraft.world.item.ItemStack>, net.minecraft.world.level.storage.loot.LootContext);
  public static it.unimi.dsi.fastutil.objects.ObjectArrayList<net.minecraft.world.item.ItemStack> modifyLoot(net.minecraft.resources.ResourceLocation, it.unimi.dsi.fastutil.objects.ObjectArrayList<net.minecraft.world.item.ItemStack>, net.minecraft.world.level.storage.loot.LootContext);
  public static java.util.List<java.lang.String> getModDataPacks();
  public static java.util.List<java.lang.String> getModDataPacksWithVanilla();
  public static java.util.Map<net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.LivingEntity>, net.minecraft.world.entity.ai.attributes.AttributeSupplier> getAttributesView();
  public static void modifyAttributes();
  public static void onEntityEnterSection(net.minecraft.world.entity.Entity, long, long);
  public static net.neoforged.neoforge.event.entity.living.LivingShieldBlockEvent onDamageBlock(net.minecraft.world.entity.LivingEntity, net.neoforged.neoforge.common.damagesource.DamageContainer, boolean);
  public static net.neoforged.neoforge.event.entity.living.LivingSwapItemsEvent$Hands onLivingSwapHandItems(net.minecraft.world.entity.LivingEntity);
  public static void writeAdditionalLevelSaveData(net.minecraft.world.level.storage.WorldData, net.minecraft.nbt.CompoundTag);
  public static void readAdditionalLevelSaveData(net.minecraft.nbt.CompoundTag, net.minecraft.world.level.storage.LevelStorageSource$LevelDirectory);
  public static java.lang.String encodeLifecycle(com.mojang.serialization.Lifecycle);
  public static com.mojang.serialization.Lifecycle parseLifecycle(java.lang.String);
  public static void saveMobEffect(net.minecraft.nbt.CompoundTag, java.lang.String, net.minecraft.world.effect.MobEffect);
  public static net.minecraft.world.effect.MobEffect loadMobEffect(net.minecraft.nbt.CompoundTag, java.lang.String, net.minecraft.world.effect.MobEffect);
  public static boolean shouldSuppressEnderManAnger(net.minecraft.world.entity.monster.EnderMan, net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack);
  public static net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix$Conversion getStructureConversion(java.lang.String);
  public static boolean checkStructureNamespace(java.lang.String);
  public static java.lang.String prefixNamespace(net.minecraft.resources.ResourceLocation);
  public static boolean canUseEntitySelectors(net.minecraft.commands.SharedSuggestionProvider);
  public static <T> net.minecraft.core.HolderLookup$RegistryLookup<T> wrapRegistryLookup(net.minecraft.core.HolderLookup$RegistryLookup<T>);
  public static void onLivingBreathe(net.minecraft.world.entity.LivingEntity, int, int);
  public static void markComponentClassAsValid(java.lang.Class<?>);
  public static void validateComponent(java.lang.Object);
  public static void onChunkUnload(net.minecraft.world.entity.ai.village.poi.PoiManager, net.minecraft.world.level.chunk.ChunkAccess);
  public static boolean canMobEffectBeApplied(net.minecraft.world.entity.LivingEntity, net.minecraft.world.effect.MobEffectInstance);
  public static boolean canMobEffectBeApplied(net.minecraft.world.entity.LivingEntity, net.minecraft.world.effect.MobEffectInstance, net.minecraft.world.entity.Entity);
  public static <T> net.minecraft.core.HolderLookup$RegistryLookup<T> resolveLookup(net.minecraft.resources.ResourceKey<? extends net.minecraft.core.Registry<T>>);
  public static net.minecraft.core.HolderLookup$Provider extractLookupProvider(net.minecraft.resources.RegistryOps<?>);
  public static net.minecraft.world.item.context.UseOnContext dispenseUseOnContext(net.minecraft.core.dispenser.BlockSource, net.minecraft.world.item.ItemStack);
  public static boolean tryDispenseShearsHarvestBlock(net.minecraft.core.dispenser.BlockSource, net.minecraft.world.item.ItemStack, net.minecraft.server.level.ServerLevel, net.minecraft.core.BlockPos);
  public static java.util.Map<net.minecraft.world.inventory.RecipeBookType, com.mojang.datafixers.util.Pair<java.lang.String, java.lang.String>> buildRecipeBookTypeTagFields(java.util.Map<net.minecraft.world.inventory.RecipeBookType, com.mojang.datafixers.util.Pair<java.lang.String, java.lang.String>>);
  public static net.minecraft.world.inventory.RecipeBookType[] getFilteredRecipeBookTypeValues();
}
