Compiled from "AbstractEntityCitizen.java"
public abstract class com.minecolonies.api.entity.citizen.AbstractEntityCitizen extends com.minecolonies.api.entity.citizen.AbstractCivilianEntity implements net.minecraft.world.MenuProvider,com.minecolonies.api.util.IItemHandlerCapProvider {
  public static final int ENTITY_AI_TICKRATE;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_LEVEL;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_TEXTURE;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_IS_FEMALE;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_COLONY_ID;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Integer> DATA_CITIZEN_ID;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.String> DATA_MODEL;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.String> DATA_RENDER_METADATA;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IS_ASLEEP;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.Boolean> DATA_IS_CHILD;
  public static final net.minecraft.network.syncher.EntityDataAccessor<net.minecraft.core.BlockPos> DATA_BED_POS;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.String> DATA_STYLE;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.String> DATA_TEXTURE_SUFFIX;
  public static final net.minecraft.network.syncher.EntityDataAccessor<java.lang.String> DATA_JOB;
  public com.minecolonies.api.entity.citizen.AbstractEntityCitizen(net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.PathfinderMob>, net.minecraft.world.level.Level);
  public static net.minecraft.world.entity.ai.attributes.AttributeSupplier$Builder getDefaultAttributes();
  public net.minecraft.world.entity.ai.goal.GoalSelector getTasks();
  public int getTicksExisted();
  public boolean canPickUpLoot();
  public boolean isControlledByLocalInstance();
  public float calculateDamageAfterAbsorbs(net.minecraft.world.damagesource.DamageSource, float);
  public net.minecraft.world.InteractionResult interactAt(net.minecraft.world.entity.player.Player, net.minecraft.world.phys.Vec3, net.minecraft.world.InteractionHand);
  public boolean isNoAi();
  public void setTexture();
  public abstract com.minecolonies.api.colony.ICitizenDataView getCitizenDataView();
  public net.minecraft.resources.ResourceLocation getTexture();
  public void setTextureDirty();
  public net.minecraft.resources.ResourceLocation getModelType();
  public boolean isFemale();
  public void setFemale(boolean);
  public com.minecolonies.core.entity.pathfinding.navigation.AbstractAdvancedPathNavigate getNavigation();
  public void pushEntities();
  public void push(net.minecraft.world.entity.Entity);
  public void onPlayerCollide(net.minecraft.world.entity.player.Player);
  public boolean isPushable();
  public void aiStep();
  public void setOwnRotation(float, float);
  public void setModelId(net.minecraft.resources.ResourceLocation);
  public void setRenderMetadata(java.lang.String);
  public int getTextureId();
  public void setTextureId(int);
  public java.lang.String getRenderMetadata();
  public net.minecraft.util.RandomSource getRandom();
  public int getOffsetTicks();
  public boolean isBlocking();
  public int getRecentlyHit();
  public boolean checkCanDropLoot();
  public abstract com.minecolonies.api.colony.requestsystem.location.ILocation getLocation();
  public abstract com.minecolonies.api.colony.ICitizenData getCitizenData();
  public abstract com.minecolonies.api.inventory.InventoryCitizen getInventoryCitizen();
  public abstract net.neoforged.neoforge.items.IItemHandler getItemHandlerCitizen();
  public abstract void setIsChild(boolean);
  public abstract void playMoveAwaySound();
  public abstract void decreaseSaturationForAction();
  public abstract void decreaseSaturationForContinuousAction();
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenExperienceHandler getCitizenExperienceHandler();
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenInventoryHandler getCitizenInventoryHandler();
  public abstract void setCitizenInventoryHandler(com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenInventoryHandler);
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenColonyHandler getCitizenColonyHandler();
  public abstract void setCitizenColonyHandler(com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenColonyHandler);
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenJobHandler getCitizenJobHandler();
  public abstract com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenSleepHandler getCitizenSleepHandler();
  public abstract float getRotationYaw();
  public abstract float getRotationPitch();
  public abstract boolean isDead();
  public abstract void setCitizenSleepHandler(com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenSleepHandler);
  public abstract void setCitizenJobHandler(com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenJobHandler);
  public abstract void setCitizenExperienceHandler(com.minecolonies.api.entity.citizen.citizenhandlers.ICitizenExperienceHandler);
  public abstract void callForHelp(net.minecraft.world.entity.Entity, int);
  public void detectEquipmentUpdates();
  public void setItemSlot(net.minecraft.world.entity.EquipmentSlot, net.minecraft.world.item.ItemStack);
  public void onArmorRemove(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.EquipmentSlot);
  public void onArmorAdd(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.EquipmentSlot);
  public void markEquipmentDirty();
  public boolean isPushedByFluid();
  public com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.ITickRateStateMachine<com.minecolonies.api.entity.ai.statemachine.states.IState> getEntityStateController();
  public boolean isSleeping();
  public net.neoforged.neoforge.items.IItemHandler getItemHandlerCap(net.minecraft.core.Direction);
  public int getTeamColor();
  public net.minecraft.network.chat.Component getDisplayName();
  public net.minecraft.world.entity.ai.navigation.PathNavigation getNavigation();
}
