Compiled from "ModBlocks.java"
public final class com.minecolonies.api.blocks.ModBlocks {
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutTownHall;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutHome;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutMiner;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutLumberjack;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutBaker;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutBuilder;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutDeliveryman;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutBlacksmith;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutStonemason;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutFarmer;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutFisherman;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutGuardTower;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutWareHouse;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutShepherd;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutCowboy;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutSwineHerder;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutChickenHerder;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutBarracks;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutBarracksTower;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutCook;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutSmeltery;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutComposter;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutLibrary;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutArchery;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutCombatAcademy;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutSawmill;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutStoneSmeltery;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutCrusher;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutSifter;
  public static com.minecolonies.api.blocks.AbstractColonyBlock<? extends com.minecolonies.api.blocks.AbstractColonyBlock<?>> blockPostBox;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutFlorist;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutEnchanter;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutUniversity;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutHospital;
  public static com.minecolonies.api.blocks.AbstractColonyBlock<? extends com.minecolonies.api.blocks.AbstractColonyBlock<?>> blockStash;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutSchool;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutGlassblower;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutDyer;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutFletcher;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutMechanic;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutPlantation;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutTavern;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutRabbitHutch;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutConcreteMixer;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutBeekeeper;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutMysticalSite;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutGraveyard;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutNetherWorker;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockSimpleQuarry;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockMediumQuarry;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutAlchemist;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutKitchen;
  public static com.minecolonies.api.blocks.AbstractBlockHut<? extends com.minecolonies.api.blocks.AbstractBlockHut<?>> blockHutGateHouse;
  public static com.minecolonies.api.blocks.decorative.AbstractBlockMinecoloniesConstructionTape<? extends com.minecolonies.api.blocks.decorative.AbstractBlockMinecoloniesConstructionTape<?>> blockConstructionTape;
  public static com.minecolonies.api.blocks.AbstractBlockMinecoloniesRack<? extends com.minecolonies.api.blocks.AbstractBlockMinecoloniesRack<?>> blockRack;
  public static com.minecolonies.api.blocks.AbstractBlockMinecoloniesGrave<? extends com.minecolonies.api.blocks.AbstractBlockMinecoloniesGrave<?>> blockGrave;
  public static com.minecolonies.api.blocks.AbstractBlockMinecoloniesNamedGrave<? extends com.minecolonies.api.blocks.AbstractBlockMinecoloniesNamedGrave<?>> blockNamedGrave;
  public static com.minecolonies.api.blocks.AbstractBlockMinecolonies<? extends com.minecolonies.api.blocks.AbstractBlockMinecolonies<?>> blockWayPoint;
  public static com.minecolonies.api.blocks.AbstractBlockBarrel<? extends com.minecolonies.api.blocks.AbstractBlockBarrel<?>> blockBarrel;
  public static com.minecolonies.api.blocks.AbstractBlockMinecoloniesDirectional<? extends com.minecolonies.api.blocks.AbstractBlockMinecoloniesDirectional<?>> blockDecorationPlaceholder;
  public static com.minecolonies.api.blocks.huts.AbstractBlockMinecoloniesDefault<? extends com.minecolonies.api.blocks.huts.AbstractBlockMinecoloniesDefault<?>> blockScarecrow;
  public static com.minecolonies.api.blocks.AbstractBlockMinecoloniesHorizontal<? extends com.minecolonies.api.blocks.AbstractBlockMinecoloniesHorizontal<?>> blockPlantationField;
  public static com.minecolonies.api.blocks.AbstractBlockMinecolonies<? extends com.minecolonies.api.blocks.AbstractBlockMinecolonies<?>> blockCompostedDirt;
  public static com.minecolonies.api.blocks.decorative.AbstractColonyFlagBanner<? extends com.minecolonies.api.blocks.decorative.AbstractColonyFlagBanner<?>> blockColonyBanner;
  public static com.minecolonies.api.blocks.decorative.AbstractColonyFlagBanner<? extends com.minecolonies.api.blocks.decorative.AbstractColonyFlagBanner<?>> blockColonyWallBanner;
  public static com.minecolonies.api.blocks.decorative.AbstractBlockGate blockIronGate;
  public static com.minecolonies.api.blocks.decorative.AbstractBlockGate blockWoodenGate;
  public static com.minecolonies.core.blocks.MinecoloniesFarmland farmland;
  public static com.minecolonies.core.blocks.MinecoloniesFarmland floodedFarmland;
  public static com.minecolonies.api.blocks.AbstractBlockMinecolonies<? extends com.minecolonies.api.blocks.AbstractBlockMinecolonies<?>> blockColonySign;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockBellPepper;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockCabbage;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockChickpea;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockDurum;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockEggplant;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockGarlic;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockOnion;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockSoyBean;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockTomato;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockRice;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockButternutSquash;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockCorn;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockMint;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockNetherPepper;
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock blockPeas;
  public static com.minecolonies.api.blocks.AbstractColonyBlock<?>[] getHuts();
  public static com.minecolonies.core.blocks.MinecoloniesCropBlock[] getCrops();
}
