Compiled from "BlockStateProvider.java"
public abstract class net.neoforged.neoforge.client.model.generators.BlockStateProvider implements net.minecraft.data.DataProvider {
  public static final com.google.common.collect.ImmutableMap<net.minecraft.core.Direction, net.minecraft.world.level.block.state.properties.Property<net.minecraft.world.level.block.state.properties.WallSide>> WALL_PROPS;
  public net.neoforged.neoforge.client.model.generators.BlockStateProvider(net.minecraft.data.PackOutput, java.lang.String, net.neoforged.neoforge.common.data.ExistingFileHelper);
  public java.util.concurrent.CompletableFuture<?> run(net.minecraft.data.CachedOutput);
  public net.neoforged.neoforge.client.model.generators.VariantBlockStateBuilder getVariantBuilder(net.minecraft.world.level.block.Block);
  public net.neoforged.neoforge.client.model.generators.MultiPartBlockStateBuilder getMultipartBuilder(net.minecraft.world.level.block.Block);
  public net.neoforged.neoforge.client.model.generators.BlockModelProvider models();
  public net.neoforged.neoforge.client.model.generators.ItemModelProvider itemModels();
  public net.minecraft.resources.ResourceLocation modLoc(java.lang.String);
  public net.minecraft.resources.ResourceLocation mcLoc(java.lang.String);
  public net.minecraft.resources.ResourceLocation blockTexture(net.minecraft.world.level.block.Block);
  public net.neoforged.neoforge.client.model.generators.ModelFile cubeAll(net.minecraft.world.level.block.Block);
  public void simpleBlock(net.minecraft.world.level.block.Block);
  public void simpleBlock(net.minecraft.world.level.block.Block, java.util.function.Function<net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ConfiguredModel[]>);
  public void simpleBlock(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void simpleBlockItem(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void simpleBlockWithItem(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void simpleBlock(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ConfiguredModel...);
  public void axisBlock(net.minecraft.world.level.block.RotatedPillarBlock);
  public void logBlock(net.minecraft.world.level.block.RotatedPillarBlock);
  public void axisBlock(net.minecraft.world.level.block.RotatedPillarBlock, net.minecraft.resources.ResourceLocation);
  public void axisBlock(net.minecraft.world.level.block.RotatedPillarBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void axisBlockWithRenderType(net.minecraft.world.level.block.RotatedPillarBlock, java.lang.String);
  public void logBlockWithRenderType(net.minecraft.world.level.block.RotatedPillarBlock, java.lang.String);
  public void axisBlockWithRenderType(net.minecraft.world.level.block.RotatedPillarBlock, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void axisBlockWithRenderType(net.minecraft.world.level.block.RotatedPillarBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void axisBlockWithRenderType(net.minecraft.world.level.block.RotatedPillarBlock, net.minecraft.resources.ResourceLocation);
  public void logBlockWithRenderType(net.minecraft.world.level.block.RotatedPillarBlock, net.minecraft.resources.ResourceLocation);
  public void axisBlockWithRenderType(net.minecraft.world.level.block.RotatedPillarBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void axisBlockWithRenderType(net.minecraft.world.level.block.RotatedPillarBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void axisBlock(net.minecraft.world.level.block.RotatedPillarBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void horizontalBlock(net.minecraft.world.level.block.Block, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void horizontalBlock(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void horizontalBlock(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ModelFile, int);
  public void horizontalBlock(net.minecraft.world.level.block.Block, java.util.function.Function<net.minecraft.world.level.block.state.BlockState, net.neoforged.neoforge.client.model.generators.ModelFile>);
  public void horizontalBlock(net.minecraft.world.level.block.Block, java.util.function.Function<net.minecraft.world.level.block.state.BlockState, net.neoforged.neoforge.client.model.generators.ModelFile>, int);
  public void horizontalFaceBlock(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void horizontalFaceBlock(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ModelFile, int);
  public void horizontalFaceBlock(net.minecraft.world.level.block.Block, java.util.function.Function<net.minecraft.world.level.block.state.BlockState, net.neoforged.neoforge.client.model.generators.ModelFile>);
  public void horizontalFaceBlock(net.minecraft.world.level.block.Block, java.util.function.Function<net.minecraft.world.level.block.state.BlockState, net.neoforged.neoforge.client.model.generators.ModelFile>, int);
  public void directionalBlock(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void directionalBlock(net.minecraft.world.level.block.Block, net.neoforged.neoforge.client.model.generators.ModelFile, int);
  public void directionalBlock(net.minecraft.world.level.block.Block, java.util.function.Function<net.minecraft.world.level.block.state.BlockState, net.neoforged.neoforge.client.model.generators.ModelFile>);
  public void directionalBlock(net.minecraft.world.level.block.Block, java.util.function.Function<net.minecraft.world.level.block.state.BlockState, net.neoforged.neoforge.client.model.generators.ModelFile>, int);
  public void stairsBlock(net.minecraft.world.level.block.StairBlock, net.minecraft.resources.ResourceLocation);
  public void stairsBlock(net.minecraft.world.level.block.StairBlock, java.lang.String, net.minecraft.resources.ResourceLocation);
  public void stairsBlock(net.minecraft.world.level.block.StairBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void stairsBlock(net.minecraft.world.level.block.StairBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void stairsBlockWithRenderType(net.minecraft.world.level.block.StairBlock, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void stairsBlockWithRenderType(net.minecraft.world.level.block.StairBlock, java.lang.String, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void stairsBlockWithRenderType(net.minecraft.world.level.block.StairBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void stairsBlockWithRenderType(net.minecraft.world.level.block.StairBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void stairsBlockWithRenderType(net.minecraft.world.level.block.StairBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void stairsBlockWithRenderType(net.minecraft.world.level.block.StairBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void stairsBlockWithRenderType(net.minecraft.world.level.block.StairBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void stairsBlockWithRenderType(net.minecraft.world.level.block.StairBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void stairsBlock(net.minecraft.world.level.block.StairBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void slabBlock(net.minecraft.world.level.block.SlabBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void slabBlock(net.minecraft.world.level.block.SlabBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void slabBlock(net.minecraft.world.level.block.SlabBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void buttonBlock(net.minecraft.world.level.block.ButtonBlock, net.minecraft.resources.ResourceLocation);
  public void buttonBlock(net.minecraft.world.level.block.ButtonBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void pressurePlateBlock(net.minecraft.world.level.block.PressurePlateBlock, net.minecraft.resources.ResourceLocation);
  public void pressurePlateBlock(net.minecraft.world.level.block.PressurePlateBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void signBlock(net.minecraft.world.level.block.StandingSignBlock, net.minecraft.world.level.block.WallSignBlock, net.minecraft.resources.ResourceLocation);
  public void signBlock(net.minecraft.world.level.block.StandingSignBlock, net.minecraft.world.level.block.WallSignBlock, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void hangingSignBlock(net.minecraft.world.level.block.CeilingHangingSignBlock, net.minecraft.world.level.block.WallHangingSignBlock, net.minecraft.resources.ResourceLocation);
  public void hangingSignBlock(net.minecraft.world.level.block.CeilingHangingSignBlock, net.minecraft.world.level.block.WallHangingSignBlock, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void fourWayBlock(net.minecraft.world.level.block.CrossCollisionBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void fourWayMultipart(net.neoforged.neoforge.client.model.generators.MultiPartBlockStateBuilder, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void fenceBlock(net.minecraft.world.level.block.FenceBlock, net.minecraft.resources.ResourceLocation);
  public void fenceBlock(net.minecraft.world.level.block.FenceBlock, java.lang.String, net.minecraft.resources.ResourceLocation);
  public void fenceBlockWithRenderType(net.minecraft.world.level.block.FenceBlock, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void fenceBlockWithRenderType(net.minecraft.world.level.block.FenceBlock, java.lang.String, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void fenceBlockWithRenderType(net.minecraft.world.level.block.FenceBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void fenceBlockWithRenderType(net.minecraft.world.level.block.FenceBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void fenceGateBlock(net.minecraft.world.level.block.FenceGateBlock, net.minecraft.resources.ResourceLocation);
  public void fenceGateBlock(net.minecraft.world.level.block.FenceGateBlock, java.lang.String, net.minecraft.resources.ResourceLocation);
  public void fenceGateBlockWithRenderType(net.minecraft.world.level.block.FenceGateBlock, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void fenceGateBlockWithRenderType(net.minecraft.world.level.block.FenceGateBlock, java.lang.String, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void fenceGateBlockWithRenderType(net.minecraft.world.level.block.FenceGateBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void fenceGateBlockWithRenderType(net.minecraft.world.level.block.FenceGateBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void fenceGateBlock(net.minecraft.world.level.block.FenceGateBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void wallBlock(net.minecraft.world.level.block.WallBlock, net.minecraft.resources.ResourceLocation);
  public void wallBlock(net.minecraft.world.level.block.WallBlock, java.lang.String, net.minecraft.resources.ResourceLocation);
  public void wallBlockWithRenderType(net.minecraft.world.level.block.WallBlock, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void wallBlockWithRenderType(net.minecraft.world.level.block.WallBlock, java.lang.String, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void wallBlockWithRenderType(net.minecraft.world.level.block.WallBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void wallBlockWithRenderType(net.minecraft.world.level.block.WallBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void wallBlock(net.minecraft.world.level.block.WallBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void paneBlock(net.minecraft.world.level.block.IronBarsBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void paneBlock(net.minecraft.world.level.block.IronBarsBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void paneBlockWithRenderType(net.minecraft.world.level.block.IronBarsBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void paneBlockWithRenderType(net.minecraft.world.level.block.IronBarsBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void paneBlockWithRenderType(net.minecraft.world.level.block.IronBarsBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void paneBlockWithRenderType(net.minecraft.world.level.block.IronBarsBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void paneBlock(net.minecraft.world.level.block.IronBarsBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void doorBlock(net.minecraft.world.level.block.DoorBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void doorBlock(net.minecraft.world.level.block.DoorBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void doorBlockWithRenderType(net.minecraft.world.level.block.DoorBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void doorBlockWithRenderType(net.minecraft.world.level.block.DoorBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, java.lang.String);
  public void doorBlockWithRenderType(net.minecraft.world.level.block.DoorBlock, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void doorBlockWithRenderType(net.minecraft.world.level.block.DoorBlock, java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public void doorBlock(net.minecraft.world.level.block.DoorBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile);
  public void trapdoorBlock(net.minecraft.world.level.block.TrapDoorBlock, net.minecraft.resources.ResourceLocation, boolean);
  public void trapdoorBlock(net.minecraft.world.level.block.TrapDoorBlock, java.lang.String, net.minecraft.resources.ResourceLocation, boolean);
  public void trapdoorBlockWithRenderType(net.minecraft.world.level.block.TrapDoorBlock, net.minecraft.resources.ResourceLocation, boolean, java.lang.String);
  public void trapdoorBlockWithRenderType(net.minecraft.world.level.block.TrapDoorBlock, java.lang.String, net.minecraft.resources.ResourceLocation, boolean, java.lang.String);
  public void trapdoorBlockWithRenderType(net.minecraft.world.level.block.TrapDoorBlock, net.minecraft.resources.ResourceLocation, boolean, net.minecraft.resources.ResourceLocation);
  public void trapdoorBlockWithRenderType(net.minecraft.world.level.block.TrapDoorBlock, java.lang.String, net.minecraft.resources.ResourceLocation, boolean, net.minecraft.resources.ResourceLocation);
  public void trapdoorBlock(net.minecraft.world.level.block.TrapDoorBlock, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, net.neoforged.neoforge.client.model.generators.ModelFile, boolean);
  public java.lang.String getName();
}
