Compiled from "ModelProvider.java"
public abstract class net.neoforged.neoforge.client.model.generators.ModelProvider<T extends net.neoforged.neoforge.client.model.generators.ModelBuilder<T>> implements net.minecraft.data.DataProvider {
  public static final java.lang.String BLOCK_FOLDER;
  public static final java.lang.String ITEM_FOLDER;
  public static final net.neoforged.neoforge.common.data.ExistingFileHelper$ResourceType TEXTURE;
  public final java.util.Map<net.minecraft.resources.ResourceLocation, T> generatedModels;
  public final net.neoforged.neoforge.common.data.ExistingFileHelper existingFileHelper;
  public net.neoforged.neoforge.client.model.generators.ModelProvider(net.minecraft.data.PackOutput, java.lang.String, java.lang.String, java.util.function.Function<net.minecraft.resources.ResourceLocation, T>, net.neoforged.neoforge.common.data.ExistingFileHelper);
  public net.neoforged.neoforge.client.model.generators.ModelProvider(net.minecraft.data.PackOutput, java.lang.String, java.lang.String, java.util.function.BiFunction<net.minecraft.resources.ResourceLocation, net.neoforged.neoforge.common.data.ExistingFileHelper, T>, net.neoforged.neoforge.common.data.ExistingFileHelper);
  public T getBuilder(java.lang.String);
  public net.minecraft.resources.ResourceLocation modLoc(java.lang.String);
  public net.minecraft.resources.ResourceLocation mcLoc(java.lang.String);
  public T withExistingParent(java.lang.String, java.lang.String);
  public T withExistingParent(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T cube(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T singleTexture(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T singleTexture(java.lang.String, net.minecraft.resources.ResourceLocation, java.lang.String, net.minecraft.resources.ResourceLocation);
  public T cubeAll(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T cubeTop(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T cubeBottomTop(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T cubeColumn(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T cubeColumnHorizontal(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T orientableVertical(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T orientableWithBottom(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T orientable(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T crop(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T cross(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T stairs(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T stairsOuter(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T stairsInner(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T slab(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T slabTop(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T button(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T buttonPressed(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T buttonInventory(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T pressurePlate(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T pressurePlateDown(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T sign(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T fencePost(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T fenceSide(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T fenceInventory(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T fenceGate(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T fenceGateOpen(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T fenceGateWall(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T fenceGateWallOpen(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T wallPost(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T wallSide(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T wallSideTall(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T wallInventory(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T panePost(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T paneSide(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T paneSideAlt(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T paneNoSide(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T paneNoSideAlt(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T doorBottomLeft(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T doorBottomLeftOpen(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T doorBottomRight(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T doorBottomRightOpen(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T doorTopLeft(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T doorTopLeftOpen(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T doorTopRight(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T doorTopRightOpen(java.lang.String, net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation);
  public T trapdoorBottom(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T trapdoorTop(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T trapdoorOpen(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T trapdoorOrientableBottom(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T trapdoorOrientableTop(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T trapdoorOrientableOpen(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T torch(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T torchWall(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T carpet(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T leaves(java.lang.String, net.minecraft.resources.ResourceLocation);
  public T nested();
  public net.neoforged.neoforge.client.model.generators.ModelFile$ExistingModelFile getExistingFile(net.minecraft.resources.ResourceLocation);
  public java.util.concurrent.CompletableFuture<?> run(net.minecraft.data.CachedOutput);
}
