Compiled from "BlockPosUtil.java"
public final class com.minecolonies.api.util.BlockPosUtil {
  public static final java.util.List<net.minecraft.core.Direction> HORIZONTAL_DIRS;
  public static final net.minecraft.core.BlockPos SAFE_ZERO;
  public static final java.util.function.BiPredicate<net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos> SOLID_AIR_POS_SELECTOR;
  public static final java.util.function.BiPredicate<net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos> DOUBLE_AIR_POS_SELECTOR;
  public static net.minecraft.nbt.CompoundTag write(net.minecraft.nbt.CompoundTag, java.lang.String, net.minecraft.core.BlockPos);
  public static net.minecraft.nbt.CompoundTag writeOptional(net.minecraft.nbt.CompoundTag, java.lang.String, net.minecraft.core.BlockPos);
  public static net.minecraft.core.BlockPos getRandomPosAround(net.minecraft.core.BlockPos, int);
  public static net.minecraft.core.BlockPos getRandomPosition(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.core.BlockPos, int, int);
  public static net.minecraft.core.BlockPos getRandomPosition(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.core.BlockPos, int, int, boolean);
  public static net.minecraft.core.BlockPos read(net.minecraft.nbt.CompoundTag, java.lang.String);
  public static net.minecraft.core.BlockPos readOrNull(net.minecraft.nbt.CompoundTag, java.lang.String);
  public static void writeToListNBT(net.minecraft.nbt.ListTag, net.minecraft.core.BlockPos);
  public static void writePosListToNBT(net.minecraft.nbt.CompoundTag, java.lang.String, java.util.List<net.minecraft.core.BlockPos>);
  public static java.util.List<net.minecraft.core.BlockPos> readPosListFromNBT(net.minecraft.nbt.CompoundTag, java.lang.String);
  public static net.minecraft.core.BlockPos readFromListNBT(net.minecraft.nbt.ListTag, int);
  public static net.minecraft.core.BlockPos getBlockPosOfString(java.lang.String);
  public static java.lang.String getString(net.minecraft.core.BlockPos);
  public static net.minecraft.core.BlockPos findLand(net.minecraft.core.BlockPos, net.minecraft.world.level.Level);
  public static double getValidHeight(net.minecraft.world.phys.Vec3, net.minecraft.world.level.Level);
  public static long getDistanceSquared(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static long getDistance2D(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static int getMaxDistance2D(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static double getDistance(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static long getDistanceSquared2D(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static int distManhattan(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static int distManhattan(net.minecraft.core.BlockPos, int, int, int);
  public static int distManhattan(int, int, int, int, int, int);
  public static int distSqr(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static int distSqr(net.minecraft.core.BlockPos, int, int, int);
  public static int distSqr(int, int, int, int, int, int);
  public static double dist(net.minecraft.core.BlockPos, int, int, int);
  public static double dist(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static double dist(int, int, int, int, int, int);
  public static net.minecraft.world.level.levelgen.structure.BoundingBox getChunkAlignedBB(net.minecraft.core.BlockPos, int);
  public static net.minecraft.world.level.block.entity.BlockEntity getTileEntity(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public static java.util.List<net.minecraft.world.item.ItemStack> getBlockDrops(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, int, net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity);
  public static net.minecraft.world.level.block.Block getBlock(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public static net.minecraft.world.level.block.state.BlockState getBlockState(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public static boolean setBlock(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, int);
  public static void set(net.minecraft.core.BlockPos$MutableBlockPos, net.minecraft.core.BlockPos);
  public static boolean equals(net.minecraft.core.BlockPos, int, int, int);
  public static boolean equals(int, int, int, int, int, int);
  public static boolean equals(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static net.minecraft.core.BlockPos fromEntity(net.minecraft.world.entity.Entity);
  public static net.minecraft.core.BlockPos getFloor(net.minecraft.core.BlockPos, net.minecraft.world.level.Level);
  public static net.minecraft.core.BlockPos getFloor(net.minecraft.core.BlockPos$MutableBlockPos, int, net.minecraft.world.level.Level);
  public static net.minecraft.core.Direction getFacing(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static net.minecraft.core.Direction getXZFacing(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static net.minecraft.core.Direction getXZFacing(int, int, int, int);
  public static net.minecraft.core.Direction directionFromDelta(int, int, int);
  public static com.minecolonies.api.util.BlockPosUtil$DirectionResult calcDirection(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static net.minecraft.core.BlockPos findAround(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, int, int, java.util.function.BiPredicate<net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos>);
  public static net.minecraft.core.BlockPos findSpawnPosAround(net.minecraft.world.level.Level, net.minecraft.core.BlockPos);
  public static net.minecraft.core.BlockPos getFurthestCorner(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public static boolean isInArea(net.minecraft.core.BlockPos, net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
}
