Compiled from "InventoryUtils.java"
public class com.minecolonies.api.util.InventoryUtils {
  public static java.util.List<net.minecraft.world.item.ItemStack> filterItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.level.block.Block);
  public static java.util.List<net.minecraft.world.item.ItemStack> filterItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static net.minecraft.world.item.Item getItemFromBlock(net.minecraft.world.level.block.Block);
  public static java.util.List<net.minecraft.world.item.ItemStack> filterItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.Item);
  public static int findFirstSlotInItemHandlerWith(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.level.block.Block);
  public static int findFirstSlotInItemHandlerWith(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.Item);
  public static int findFirstSlotInItemHandlerWith(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static boolean shrinkItemCountInItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static java.util.List<java.lang.Integer> findAllSlotsInItemHandlerWith(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int getItemCountInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.level.block.Block);
  public static int getItemCountInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.Item);
  public static int getItemCountInItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int getItemCountInItemHandlers(java.util.Collection<net.neoforged.neoforge.items.IItemHandler>, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static boolean hasItemInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.level.block.Block);
  public static boolean hasItemInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.Item);
  public static boolean hasItemInItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static boolean isItemHandlerFull(net.neoforged.neoforge.items.IItemHandler);
  public static int getFirstOpenSlotFromItemHandler(net.neoforged.neoforge.items.IItemHandler);
  public static long openSlotCount(net.neoforged.neoforge.items.IItemHandler);
  public static net.minecraft.world.item.ItemStack forceItemStackToItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int getAmountOfStacksInItemHandler(net.neoforged.neoforge.items.IItemHandler);
  public static java.util.List<net.minecraft.world.item.ItemStack> getItemHandlerAsList(net.neoforged.neoforge.items.IItemHandler);
  public static java.util.List<net.minecraft.world.item.ItemStack> filterProvider(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.level.block.Block);
  public static java.util.List<net.minecraft.world.item.ItemStack> filterProvider(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static java.util.Set<net.neoforged.neoforge.items.IItemHandler> getItemHandlersFromProvider(com.minecolonies.api.util.IItemHandlerCapProvider);
  public static java.util.List<net.minecraft.world.item.ItemStack> filterProvider(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.item.Item);
  public static int findFirstSlotInProviderWith(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.level.block.Block);
  public static int findFirstSlotInProviderWith(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.item.Item);
  public static java.util.Map<net.neoforged.neoforge.items.IItemHandler, java.util.List<java.lang.Integer>> findAllSlotsInProviderWith(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int findFirstSlotInProviderNotEmptyWith(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int findFirstSlotInProviderNotEmptyWith(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.List<java.util.function.Predicate<net.minecraft.world.item.ItemStack>>);
  public static int findFirstSlotInItemHandlerNotEmptyWith(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int getItemCountInProvider(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.level.block.Block);
  public static int getItemCountInProvider(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.item.Item);
  public static int getItemCountInProvider(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int getDurabilityInProvider(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int hasBuildingEnoughElseCount(com.minecolonies.api.colony.buildings.ICommonBuilding, com.minecolonies.api.crafting.ItemStorage, int);
  public static int hasBuildingEnoughElseCount(com.minecolonies.api.colony.buildings.ICommonBuilding, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int);
  public static int getCountFromBuilding(com.minecolonies.api.colony.buildings.IBuilding, java.util.List<com.minecolonies.api.crafting.ItemStorage>);
  public static int getCountFromBuilding(com.minecolonies.api.colony.buildings.IBuilding, com.minecolonies.api.crafting.ItemStorage);
  public static int countEmptySlotsInBuilding(com.minecolonies.api.colony.buildings.IBuilding);
  public static boolean isBuildingFull(com.minecolonies.api.colony.buildings.IBuilding);
  public static int getCountFromBuilding(com.minecolonies.api.colony.buildings.IBuilding, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int getCountFromBuildingWithLimit(com.minecolonies.api.colony.buildings.IBuilding, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, java.util.function.Function<net.minecraft.world.item.ItemStack, java.lang.Integer>);
  public static boolean hasItemInProvider(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.level.block.Block);
  public static boolean hasItemInProvider(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.item.Item);
  public static boolean hasItemInProvider(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static boolean isProviderFull(com.minecolonies.api.util.IItemHandlerCapProvider);
  public static int getFirstOpenSlotFromProvider(com.minecolonies.api.util.IItemHandlerCapProvider);
  public static boolean addItemStackToProvider(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.item.ItemStack);
  public static boolean addItemStackToItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack);
  public static net.minecraft.world.item.ItemStack addItemStackToProviderWithResult(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.item.ItemStack);
  public static net.minecraft.world.item.ItemStack addItemStackToItemHandlerWithResult(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack);
  public static net.minecraft.world.item.ItemStack forceItemStackToProvider(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.item.ItemStack, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int getAmountOfStacksInProvider(com.minecolonies.api.util.IItemHandlerCapProvider);
  public static java.util.List<net.minecraft.world.item.ItemStack> getProviderAsList(com.minecolonies.api.util.IItemHandlerCapProvider);
  public static boolean hasProviderIItemHandler(com.minecolonies.api.util.IItemHandlerCapProvider);
  public static boolean isProviderSided(com.minecolonies.api.util.IItemHandlerCapProvider);
  public static java.util.List<net.minecraft.world.item.ItemStack> getInventoryAsListFromProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction);
  public static java.util.List<net.minecraft.world.item.ItemStack> filterItemHandlerFromProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, net.minecraft.world.level.block.Block);
  public static java.util.List<net.minecraft.world.item.ItemStack> filterItemHandlerFromProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, net.minecraft.world.item.Item, int);
  public static java.util.List<net.minecraft.world.item.ItemStack> filterItemHandlerFromProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int findFirstSlotInProviderForSideWith(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, net.minecraft.world.level.block.Block, int);
  public static int findFirstSlotInProviderForSideWith(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, net.minecraft.world.item.Item);
  public static int findFirstSlotInProviderForSideWith(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static int getItemCountInProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, net.minecraft.world.level.block.Block);
  public static int getItemCountInProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, net.minecraft.world.item.Item);
  public static int getItemCountInProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static boolean hasItemInProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, net.minecraft.world.level.block.Block);
  public static boolean hasItemInProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, net.minecraft.world.item.Item);
  public static boolean hasItemInProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static boolean isProviderFull(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction);
  public static int getFirstOpenSlotFromProviderForSide(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.core.Direction);
  public static boolean isEquipmentInItemHandler(net.neoforged.neoforge.items.IItemHandler, com.minecolonies.api.equipment.registry.EquipmentTypeEntry, int, int);
  public static void clearItemHandler(net.neoforged.neoforge.items.IItemHandler);
  public static int getFirstSlotOfItemHandlerContainingEquipment(net.neoforged.neoforge.items.IItemHandler, com.minecolonies.api.equipment.registry.EquipmentTypeEntry, int, int);
  public static boolean hasItemHandlerEquipmentWithLevel(net.neoforged.neoforge.items.IItemHandler, com.minecolonies.api.equipment.registry.EquipmentTypeEntry, int, int);
  public static boolean transferItemStackIntoNextFreeSlotInProvider(net.neoforged.neoforge.items.IItemHandler, int, com.minecolonies.api.util.IItemHandlerCapProvider);
  public static boolean transferItemStackIntoNextFreeSlotInItemHandler(net.neoforged.neoforge.items.IItemHandler, int, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferXOfItemStackIntoNextFreeSlotInItemHandler(net.neoforged.neoforge.items.IItemHandler, int, int, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferItemStackIntoNextBestSlotInItemHandler(net.neoforged.neoforge.items.IItemHandler, int, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferItemStackIntoNextBestSlotInItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferItemStackIntoNextBestSlotInItemHandler(com.minecolonies.api.colony.buildings.IBuilding, com.minecolonies.api.crafting.ItemStorage, int, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferItemStackIntoNextBestSlotInItemHandler(com.minecolonies.api.colony.buildings.IBuilding, com.minecolonies.api.crafting.ItemStorage, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferItemStackIntoNextBestSlotInItemHandler(net.minecraft.world.item.ItemStack, net.neoforged.neoforge.items.IItemHandler);
  public static net.minecraft.world.item.ItemStack transferItemStackIntoNextBestSlotInItemHandlerWithResult(net.minecraft.world.item.ItemStack, net.neoforged.neoforge.items.IItemHandler);
  public static void mergeItemStackIntoNextBestSlotInItemHandlers(net.neoforged.neoforge.items.IItemHandler, int, net.neoforged.neoforge.items.IItemHandler);
  public static net.minecraft.world.item.ItemStack mergeItemStackIntoNextBestSlotInItemHandlers(net.minecraft.world.item.ItemStack, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferXOfFirstSlotInProviderWithIntoNextFreeSlotInProvider(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int, com.minecolonies.api.util.IItemHandlerCapProvider);
  public static int transferXOfFirstSlotInProviderWithIntoNextFreeSlotInProviderWithResult(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int, com.minecolonies.api.util.IItemHandlerCapProvider);
  public static boolean transferXOfFirstSlotInProviderWithIntoNextFreeSlotInItemHandler(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int, net.neoforged.neoforge.items.IItemHandler);
  public static int transferXOfFirstSlotInProviderWithIntoNextFreeSlotInItemHandlerWithResult(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferXOfFirstSlotInItemHandlerWithIntoNextFreeSlotInItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int, net.neoforged.neoforge.items.IItemHandler);
  public static int transferXOfFirstSlotInItemHandlerWithIntoNextFreeSlotInItemHandlerWithResult(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int, net.neoforged.neoforge.items.IItemHandler);
  public static int transferXInItemHandlerIntoSlotInItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int, net.neoforged.neoforge.items.IItemHandler, int);
  public static int transferXOfFirstSlotInItemHandlerWithIntoInItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int, net.neoforged.neoforge.items.IItemHandler, int);
  public static boolean transferItemStackIntoNextFreeSlotFromProvider(com.minecolonies.api.util.IItemHandlerCapProvider, int, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferItemStackIntoNextFreeSlotFromItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferXOfItemStackIntoNextFreeSlotFromProvider(com.minecolonies.api.util.IItemHandlerCapProvider, int, int, net.neoforged.neoforge.items.IItemHandler);
  public static boolean transferItemStackIntoNextBestSlotFromProvider(com.minecolonies.api.util.IItemHandlerCapProvider, int, net.neoforged.neoforge.items.IItemHandler);
  public static boolean swapItemStacksInItemHandlers(net.neoforged.neoforge.items.IItemHandler, int, net.neoforged.neoforge.items.IItemHandler, int);
  public static boolean removeStacksFromProvider(com.minecolonies.api.util.IItemHandlerCapProvider, java.util.List<net.minecraft.world.item.ItemStack>);
  public static boolean removeStacksFromItemHandler(net.neoforged.neoforge.items.IItemHandler, java.util.List<net.minecraft.world.item.ItemStack>);
  public static boolean tryRemoveStackFromItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack);
  public static void removeStackFromItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack, int);
  public static int findSlotInProviderNotFullWithItem(com.minecolonies.api.util.IItemHandlerCapProvider, net.minecraft.world.item.Item, int);
  public static int findSlotInItemHandlerNotFullWithItem(net.neoforged.neoforge.items.IItemHandler, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, int);
  public static boolean findSlotInItemHandlerNotFullWithItem(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack);
  public static void dropItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.level.Level, int, int, int);
  public static boolean transferAllItemHandler(net.neoforged.neoforge.items.IItemHandler, net.neoforged.neoforge.items.IItemHandler);
  public static void spawnItemStack(net.minecraft.world.level.Level, double, double, double, net.minecraft.world.item.ItemStack);
  public static int getItemCountInStackLick(java.util.List<net.minecraft.world.item.ItemStack>, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static boolean areAllItemsInItemHandler(java.util.List<net.minecraft.world.item.ItemStack>, net.neoforged.neoforge.items.IItemHandler);
  public static boolean areAllItemsInProvider(java.util.List<net.minecraft.world.item.ItemStack>, com.minecolonies.api.util.IItemHandlerCapProvider);
  public static boolean areAllItemsInItemHandlerList(java.util.List<net.minecraft.world.item.ItemStack>, java.util.Collection<net.neoforged.neoforge.items.IItemHandler>);
  public static java.util.Map<net.minecraft.world.item.ItemStack, java.lang.Integer> getMergedCountedStacksFromList(java.util.List<net.minecraft.world.item.ItemStack>);
  public static java.util.List<net.minecraft.world.item.ItemStack> splitMergedCountedStacksIntoMaxContentStacks(java.util.Map<net.minecraft.world.item.ItemStack, java.lang.Integer>);
  public static java.util.List<net.minecraft.world.item.ItemStack> getContainedFromItemHandler(java.util.List<net.minecraft.world.item.ItemStack>, net.neoforged.neoforge.items.IItemHandler);
  public static java.util.List<net.minecraft.world.item.ItemStack> processItemStackListAndMerge(java.util.List<net.minecraft.world.item.ItemStack>);
  public static boolean moveItemStacksWithPossibleSwap(net.neoforged.neoforge.items.IItemHandler, java.util.Collection<net.neoforged.neoforge.items.IItemHandler>, java.util.List<net.minecraft.world.item.ItemStack>, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static void reduceStackInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack);
  public static void reduceStackInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack, int);
  public static void reduceBucketAwareStackInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack);
  public static void reduceBucketAwareStackInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack, int);
  public static boolean attemptReduceStackInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack, int);
  public static boolean attemptReduceStackInItemHandler(net.neoforged.neoforge.items.IItemHandler, net.minecraft.world.item.ItemStack, int, boolean, boolean);
  public static java.util.Map<com.minecolonies.api.crafting.ItemStorage, com.minecolonies.api.crafting.ItemStorage> getAllItemsForProviders(com.minecolonies.api.util.IItemHandlerCapProvider, net.neoforged.neoforge.items.IItemHandler...);
  public static java.util.Map<com.minecolonies.api.crafting.ItemStorage, com.minecolonies.api.crafting.ItemStorage> getAllItemsForProviders(net.neoforged.neoforge.items.IItemHandler...);
  public static java.util.Map<com.minecolonies.api.crafting.ItemStorage, com.minecolonies.api.crafting.ItemStorage> getAllItemsForProviders(java.util.Set<net.neoforged.neoforge.items.IItemHandler>);
  public static boolean doStorageSetsMatch(java.util.Map<com.minecolonies.api.crafting.ItemStorage, com.minecolonies.api.crafting.ItemStorage>, java.util.Map<com.minecolonies.api.crafting.ItemStorage, com.minecolonies.api.crafting.ItemStorage>, boolean);
  public static it.unimi.dsi.fastutil.objects.Object2IntMap<net.minecraft.world.item.ItemStack> transferFoodUpToSaturation(com.minecolonies.api.util.IItemHandlerCapProvider, net.neoforged.neoforge.items.IItemHandler, int, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static boolean putItemToHotbarAndSelectOrDrop(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.player.Player);
  public static boolean putItemToHotbarAndSelectOrDropMessage(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.player.Player);
  public static net.minecraft.world.item.ItemStack getOrCreateItemAndPutToHotbarAndSelectOrDrop(net.minecraft.world.item.Item, net.minecraft.world.entity.player.Player, java.util.function.Supplier<net.minecraft.world.item.ItemStack>, boolean);
  public static boolean hasEnoughInProvider(net.minecraft.world.level.block.entity.BlockEntity, net.minecraft.world.item.ItemStack, int);
  public static java.util.List<net.minecraft.world.item.ItemStack> getBuildingInventory(com.minecolonies.api.colony.buildings.IBuilding);
  public static net.minecraft.world.item.ItemStack getFirstMatch(java.util.List<net.minecraft.world.item.ItemStack>, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
  public static com.minecolonies.api.crafting.ItemStorage reduceBuildingThenPlayerInventory(com.minecolonies.api.colony.buildings.IBuilding, net.minecraft.world.entity.player.Player, com.minecolonies.api.crafting.ItemStorage, java.util.function.Predicate<net.minecraft.world.item.ItemStack>, java.util.function.Predicate<net.minecraft.world.item.ItemStack>);
}
