Compiled from "ItemStackUtils.java"
public final class com.minecolonies.api.util.ItemStackUtils {
  public static final net.minecraft.world.item.ItemStack EMPTY;
  public static final java.util.function.Predicate<net.minecraft.world.item.ItemStack> EMPTY_PREDICATE;
  public static final java.util.function.Predicate<net.minecraft.world.item.ItemStack> NOT_EMPTY_PREDICATE;
  public static java.util.HashMap<net.minecraft.world.item.Item, java.util.Set<net.minecraft.core.component.DataComponentType<?>>> CHECKED_NBT_KEYS;
  public static final java.util.function.Predicate<net.minecraft.world.item.ItemStack> IS_ANY_FOOD;
  public static final java.util.function.Predicate<net.minecraft.world.item.ItemStack> ISFOOD;
  public static java.util.function.Predicate<net.minecraft.world.item.ItemStack> IS_SMELTABLE;
  public static java.util.function.Predicate<net.minecraft.world.item.ItemStack> ISCOOKABLE;
  public static final java.util.function.Predicate<net.minecraft.world.item.ItemStack> IS_COMPOST;
  public static java.util.List<com.minecolonies.api.crafting.ItemStorage> getListOfStackForEntity(net.minecraft.world.entity.Entity, net.minecraft.world.entity.Entity);
  public static boolean hasEquipmentLevel(net.minecraft.world.item.ItemStack, com.minecolonies.api.equipment.registry.EquipmentTypeEntry, int, int);
  public static boolean isEmpty(net.minecraft.world.item.ItemStack);
  public static boolean isNotEmpty(net.minecraft.world.item.ItemStack);
  public static boolean verifyEquipmentLevel(net.minecraft.world.item.ItemStack, int, int, int);
  public static int getMaxEnchantmentLevel(net.minecraft.world.item.ItemStack);
  public static int getArmorLevel(net.minecraft.world.item.ItemStack);
  public static boolean isBetterEquipment(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack);
  public static int getFortuneOf(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level);
  public static boolean doesItemServeAsWeapon(net.minecraft.world.item.ItemStack);
  public static net.minecraft.network.chat.MutableComponent swapArmorGrade(int);
  public static net.minecraft.network.chat.MutableComponent swapToolGrade(int);
  public static java.lang.Boolean areItemStacksMergable(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack);
  public static java.lang.Boolean compareItemStacksIgnoreStackSize(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack);
  public static int getSize(net.minecraft.world.item.ItemStack);
  public static int getDurability(net.minecraft.world.item.ItemStack);
  public static boolean compareItemStacksIgnoreStackSize(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, boolean, boolean);
  public static boolean compareItemStacksIgnoreStackSize(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, boolean, boolean, boolean);
  public static boolean compareItemStacksIgnoreStackSize(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, boolean, boolean, boolean, boolean);
  public static boolean compareItemStackListIgnoreStackSize(java.util.List<net.minecraft.world.item.ItemStack>, net.minecraft.world.item.ItemStack);
  public static boolean compareItemStorageListIgnoreStackSize(java.util.List<com.minecolonies.api.crafting.ItemStorage>, net.minecraft.world.item.ItemStack);
  public static boolean compareItemStackListIgnoreStackSize(java.util.List<net.minecraft.world.item.ItemStack>, net.minecraft.world.item.ItemStack, boolean, boolean);
  public static void setSize(net.minecraft.world.item.ItemStack, int);
  public static void changeSize(net.minecraft.world.item.ItemStack, int);
  public static net.minecraft.world.item.ItemStack deserializeFromNBT(net.minecraft.nbt.CompoundTag, net.minecraft.core.HolderLookup$Provider);
  public static boolean isStackSapling(net.minecraft.world.item.ItemStack);
  public static boolean hasSmeltableInFurnaceAndNoFuel(net.minecraft.world.level.block.entity.FurnaceBlockEntity);
  public static boolean hasNeitherFuelNorSmeltAble(net.minecraft.world.level.block.entity.FurnaceBlockEntity);
  public static boolean hasFuelInFurnaceAndNoSmeltable(net.minecraft.world.level.block.entity.FurnaceBlockEntity);
  public static boolean hasBrewableAndNoFuel(net.minecraft.world.level.block.entity.BrewingStandBlockEntity);
  public static boolean hasNeitherFuelNorBrewable(net.minecraft.world.level.block.entity.BrewingStandBlockEntity);
  public static boolean hasFuelAndNoBrewable(net.minecraft.world.level.block.entity.BrewingStandBlockEntity);
  public static net.minecraft.world.item.ItemStack idToItemStack(java.lang.String, net.minecraft.core.HolderLookup$Provider);
  public static com.minecolonies.api.util.Tuple<java.lang.Boolean, java.lang.String> parseIdTemplate(java.lang.String, net.minecraft.resources.ResourceLocation);
  public static boolean hasTag(net.minecraft.world.item.ItemStack);
  public static java.util.List<net.minecraft.world.item.ItemStack> allItemsPlusInventory(net.minecraft.world.entity.player.Player);
  public static void consumeFood(net.minecraft.world.item.ItemStack, com.minecolonies.api.entity.citizen.AbstractEntityCitizen, net.minecraft.world.entity.player.Player);
  public static net.minecraft.network.chat.Component getTranslatedName(net.neoforged.neoforge.common.crafting.SizedIngredient);
  public static java.util.Optional<net.minecraft.tags.TagKey<net.minecraft.world.item.Item>> getTagEquivalent(net.minecraft.world.item.ItemStack[]);
  public static double getItemStackAttributeValue(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.EquipmentSlot, net.minecraft.core.Holder<net.minecraft.world.entity.ai.attributes.Attribute>);
}
