Compiled from "QuestRegistries.java"
public class com.minecolonies.api.quests.registries.QuestRegistries {
  public static net.minecraft.resources.ResourceLocation ITEM_REWARD_ID;
  public static net.minecraft.resources.ResourceLocation SKILL_REWARD_ID;
  public static net.minecraft.resources.ResourceLocation RESEARCH_REWARD_ID;
  public static net.minecraft.resources.ResourceLocation RAID_REWARD_ID;
  public static net.minecraft.resources.ResourceLocation RELATIONSHIP_REWARD_ID;
  public static net.minecraft.resources.ResourceLocation HAPPINESS_REWARD_ID;
  public static net.minecraft.resources.ResourceLocation UNLOCK_QUEST_REWARD_ID;
  public static net.minecraft.resources.ResourceLocation QUEST_REPUTATION_REWARD_ID;
  public static net.minecraft.resources.ResourceLocation DIALOGUE_OBJECTIVE_ID;
  public static net.minecraft.resources.ResourceLocation BREAKBLOCK_OBJECTIVE_ID;
  public static net.minecraft.resources.ResourceLocation DELIVERY_OBJECTIVE_ID;
  public static net.minecraft.resources.ResourceLocation KILLENTITY_OBJECTIVE_ID;
  public static net.minecraft.resources.ResourceLocation PLACEBLOCK_OBJECTIVE_ID;
  public static net.minecraft.resources.ResourceLocation BUILD_BUILDING_OBJECTIVE_ID;
  public static net.minecraft.resources.ResourceLocation RESEARCH_OBJECTIVE_ID;
  public static net.minecraft.resources.ResourceLocation STATE_TRIGGER_ID;
  public static net.minecraft.resources.ResourceLocation RANDOM_TRIGGER_ID;
  public static net.minecraft.resources.ResourceLocation CITIZEN_TRIGGER_ID;
  public static net.minecraft.resources.ResourceLocation UNLOCK_TRIGGER_ID;
  public static net.minecraft.resources.ResourceLocation QUEST_REPUTATION_TRIGGER_ID;
  public static net.minecraft.resources.ResourceLocation WORLD_DIFFICULTY_TRIGGER_ID;
  public static net.minecraft.resources.ResourceLocation DIALOGUE_ANSWER_ID;
  public static net.minecraft.resources.ResourceLocation RETURN_ANSWER_ID;
  public static net.minecraft.resources.ResourceLocation CANCEL_ANSWER_ID;
  public static net.minecraft.resources.ResourceLocation GOTO_ANSWER_ID;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry, com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry> itemReward;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry, com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry> skillReward;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry, com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry> researchReward;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry, com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry> raidReward;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry, com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry> relationshipReward;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry, com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry> happinessReward;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry, com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry> unlockQuestReward;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry, com.minecolonies.api.quests.registries.QuestRegistries$RewardEntry> questReputationReward;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry, com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry> dialogueObjective;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry, com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry> breakBlockObjective;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry, com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry> deliveryObjective;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry, com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry> killEntityObjective;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry, com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry> placeBlockObjective;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry, com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry> buildBuildingObjective;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry, com.minecolonies.api.quests.registries.QuestRegistries$ObjectiveEntry> researchObjective;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry, com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry> stateTrigger;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry, com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry> randomTrigger;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry, com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry> citizenTrigger;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry, com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry> unlockTrigger;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry, com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry> questReputationTrigger;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry, com.minecolonies.api.quests.registries.QuestRegistries$TriggerEntry> worldDifficultyTrigger;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$DialogueAnswerEntry, com.minecolonies.api.quests.registries.QuestRegistries$DialogueAnswerEntry> dialogueAnswerResult;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$DialogueAnswerEntry, com.minecolonies.api.quests.registries.QuestRegistries$DialogueAnswerEntry> returnAnswerResult;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$DialogueAnswerEntry, com.minecolonies.api.quests.registries.QuestRegistries$DialogueAnswerEntry> cancelAnswerResult;
  public static net.neoforged.neoforge.registries.DeferredHolder<com.minecolonies.api.quests.registries.QuestRegistries$DialogueAnswerEntry, com.minecolonies.api.quests.registries.QuestRegistries$DialogueAnswerEntry> gotoAnswerResult;
  public com.minecolonies.api.quests.registries.QuestRegistries();
}
