Compiled from "IBlockStateExtension.java"
public interface net.neoforged.neoforge.common.extensions.IBlockStateExtension {
  public default float getFriction(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.world.entity.Entity);
  public default boolean hasDynamicLightEmission();
  public default int getLightEmission(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos);
  public default boolean ignitedByLava(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.core.Direction);
  public default boolean isLadder(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.world.entity.LivingEntity);
  public default boolean canHarvestBlock(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.entity.player.Player);
  public default boolean onDestroyedByPlayer(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.entity.player.Player, boolean, net.minecraft.world.level.material.FluidState);
  public default void onDestroyedByPushReaction(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.core.Direction, net.minecraft.world.level.material.FluidState);
  public default boolean isBed(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.entity.LivingEntity);
  public default java.util.Optional<net.minecraft.server.level.ServerPlayer$RespawnPosAngle> getRespawnPosition(net.minecraft.world.entity.EntityType<?>, net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, float);
  public default void setBedOccupied(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.entity.LivingEntity, boolean);
  public default net.minecraft.core.Direction getBedDirection(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos);
  public default float getExplosionResistance(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.level.Explosion);
  public default net.minecraft.world.item.ItemStack getCloneItemStack(net.minecraft.world.phys.HitResult, net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.world.entity.player.Player);
  public default boolean addLandingEffects(net.minecraft.server.level.ServerLevel, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.entity.LivingEntity, int);
  public default boolean addRunningEffects(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.entity.Entity);
  public default net.neoforged.neoforge.common.util.TriState canSustainPlant(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.core.Direction, net.minecraft.world.level.block.state.BlockState);
  public default boolean onTreeGrow(net.minecraft.world.level.LevelReader, java.util.function.BiConsumer<net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState>, net.minecraft.util.RandomSource, net.minecraft.core.BlockPos, net.minecraft.world.level.levelgen.feature.configurations.TreeConfiguration);
  public default boolean isFertile(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos);
  public default boolean isConduitFrame(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public default boolean isPortalFrame(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos);
  public default int getExpDrop(net.minecraft.world.level.LevelAccessor, net.minecraft.core.BlockPos, net.minecraft.world.level.block.entity.BlockEntity, net.minecraft.world.entity.Entity, net.minecraft.world.item.ItemStack);
  public default net.minecraft.world.level.block.state.BlockState rotate(net.minecraft.world.level.LevelAccessor, net.minecraft.core.BlockPos, net.minecraft.world.level.block.Rotation);
  public default float getEnchantPowerBonus(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos);
  public default void onNeighborChange(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public default boolean shouldCheckWeakPower(net.minecraft.world.level.SignalGetter, net.minecraft.core.BlockPos, net.minecraft.core.Direction);
  public default boolean getWeakChanges(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos);
  public default net.minecraft.world.level.block.SoundType getSoundType(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.world.entity.Entity);
  public default java.lang.Integer getBeaconColorMultiplier(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.core.BlockPos);
  public default net.minecraft.world.level.block.state.BlockState getStateAtViewpoint(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.phys.Vec3);
  public default boolean isSlimeBlock();
  public default boolean isStickyBlock();
  public default boolean canStickTo(net.minecraft.world.level.block.state.BlockState);
  public default int getFlammability(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.core.Direction);
  public default boolean isFlammable(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.core.Direction);
  public default void onCaughtFire(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.core.Direction, net.minecraft.world.entity.LivingEntity);
  public default int getFireSpreadSpeed(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.core.Direction);
  public default boolean isFireSource(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.core.Direction);
  public default boolean canEntityDestroy(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.entity.Entity);
  public default boolean isBurning(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos);
  public default net.minecraft.world.level.pathfinder.PathType getBlockPathType(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.entity.Mob);
  public default net.minecraft.world.level.pathfinder.PathType getAdjacentBlockPathType(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.entity.Mob, net.minecraft.world.level.pathfinder.PathType);
  public default boolean canDropFromExplosion(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.level.Explosion);
  public default void onBlockExploded(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.Explosion);
  public default boolean collisionExtendsVertically(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.entity.Entity);
  public default boolean shouldDisplayFluidOverlay(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos, net.minecraft.world.level.material.FluidState);
  public default net.minecraft.world.level.block.state.BlockState getToolModifiedState(net.minecraft.world.item.context.UseOnContext, net.neoforged.neoforge.common.ItemAbility, boolean);
  public default boolean isScaffolding(net.minecraft.world.entity.LivingEntity);
  public default boolean canRedstoneConnectTo(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.core.Direction);
  public default boolean hidesNeighborFace(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.core.Direction);
  public default boolean supportsExternalFaceHiding();
  public default void onBlockStateChange(net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState);
  public default boolean canBeHydrated(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos, net.minecraft.world.level.material.FluidState, net.minecraft.core.BlockPos);
  public default net.minecraft.world.level.block.state.BlockState getAppearance(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos, net.minecraft.core.Direction, net.minecraft.world.level.block.state.BlockState, net.minecraft.core.BlockPos);
  public default boolean isEmpty();
  public default net.neoforged.neoforge.common.enums.BubbleColumnDirection getBubbleColumnDirection();
  public default boolean shouldHideAdjacentFluidFace(net.minecraft.core.Direction, net.minecraft.world.level.material.FluidState);
}
