Compiled from "IItemExtension.java"
public interface net.neoforged.neoforge.common.extensions.IItemExtension {
  public default net.minecraft.world.item.component.ItemAttributeModifiers getDefaultAttributeModifiers(net.minecraft.world.item.ItemStack);
  public default boolean onDroppedByPlayer(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.player.Player);
  public default net.minecraft.network.chat.Component getHighlightTip(net.minecraft.world.item.ItemStack, net.minecraft.network.chat.Component);
  public default net.minecraft.world.InteractionResult onItemUseFirst(net.minecraft.world.item.ItemStack, net.minecraft.world.item.context.UseOnContext);
  public default boolean isPiglinCurrency(net.minecraft.world.item.ItemStack);
  public default boolean makesPiglinsNeutral(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity);
  public abstract boolean isRepairable(net.minecraft.world.item.ItemStack);
  public default float getXpRepairRatio(net.minecraft.world.item.ItemStack);
  public default void onStopUsing(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity, int);
  public default boolean onLeftClickEntity(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.player.Player, net.minecraft.world.entity.Entity);
  public default net.minecraft.world.item.ItemStack getCraftingRemainingItem(net.minecraft.world.item.ItemStack);
  public default boolean hasCraftingRemainingItem(net.minecraft.world.item.ItemStack);
  public default int getEntityLifespan(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level);
  public default boolean hasCustomEntity(net.minecraft.world.item.ItemStack);
  public default net.minecraft.world.entity.Entity createEntity(net.minecraft.world.level.Level, net.minecraft.world.entity.Entity, net.minecraft.world.item.ItemStack);
  public default boolean onEntityItemUpdate(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.item.ItemEntity);
  public default boolean doesSneakBypassUse(net.minecraft.world.item.ItemStack, net.minecraft.world.level.LevelReader, net.minecraft.core.BlockPos, net.minecraft.world.entity.player.Player);
  public default boolean canEquip(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.EquipmentSlot, net.minecraft.world.entity.LivingEntity);
  public default net.minecraft.world.entity.EquipmentSlot getEquipmentSlot(net.minecraft.world.item.ItemStack);
  public default boolean isBookEnchantable(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack);
  public default net.minecraft.resources.ResourceLocation getArmorTexture(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.Entity, net.minecraft.world.entity.EquipmentSlot, net.minecraft.world.item.ArmorMaterial$Layer, boolean);
  public default boolean onEntitySwing(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity);
  public default boolean onEntitySwing(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity, net.minecraft.world.InteractionHand);
  public default int getDamage(net.minecraft.world.item.ItemStack);
  public default int getMaxDamage(net.minecraft.world.item.ItemStack);
  public default boolean isDamaged(net.minecraft.world.item.ItemStack);
  public default void setDamage(net.minecraft.world.item.ItemStack, int);
  public default boolean canPerformAction(net.minecraft.world.item.ItemStack, net.neoforged.neoforge.common.ItemAbility);
  public default int getMaxStackSize(net.minecraft.world.item.ItemStack);
  public default int getEnchantmentValue(net.minecraft.world.item.ItemStack);
  public default boolean isPrimaryItemFor(net.minecraft.world.item.ItemStack, net.minecraft.core.Holder<net.minecraft.world.item.enchantment.Enchantment>);
  public default boolean supportsEnchantment(net.minecraft.world.item.ItemStack, net.minecraft.core.Holder<net.minecraft.world.item.enchantment.Enchantment>);
  public default int getEnchantmentLevel(net.minecraft.world.item.ItemStack, net.minecraft.core.Holder<net.minecraft.world.item.enchantment.Enchantment>);
  public default net.minecraft.world.item.enchantment.ItemEnchantments getAllEnchantments(net.minecraft.world.item.ItemStack, net.minecraft.core.HolderLookup$RegistryLookup<net.minecraft.world.item.enchantment.Enchantment>);
  public default boolean shouldCauseReequipAnimation(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, boolean);
  public default boolean shouldCauseBlockBreakReset(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack);
  public default boolean canContinueUsing(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack);
  public default java.lang.String getCreatorModId(net.minecraft.world.item.ItemStack);
  public default boolean canDisableShield(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity, net.minecraft.world.entity.LivingEntity);
  public default int getBurnTime(net.minecraft.world.item.ItemStack, net.minecraft.world.item.crafting.RecipeType<?>);
  public default void onAnimalArmorTick(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level, net.minecraft.world.entity.Mob);
  public default <T extends net.minecraft.world.entity.LivingEntity> int damageItem(net.minecraft.world.item.ItemStack, int, T, java.util.function.Consumer<net.minecraft.world.item.Item>);
  public default void onDestroyed(net.minecraft.world.entity.item.ItemEntity, net.minecraft.world.damagesource.DamageSource);
  public default boolean isEnderMask(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.player.Player, net.minecraft.world.entity.monster.EnderMan);
  public default boolean canElytraFly(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity);
  public default boolean elytraFlightTick(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity, int);
  public default boolean canWalkOnPowderedSnow(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity);
  public default boolean isDamageable(net.minecraft.world.item.ItemStack);
  public default net.minecraft.world.phys.AABB getSweepHitBox(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.player.Player, net.minecraft.world.entity.Entity);
  public default net.minecraft.world.food.FoodProperties getFoodProperties(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.LivingEntity);
  public default boolean isNotReplaceableByPickAction(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.player.Player, int);
  public default boolean canGrindstoneRepair(net.minecraft.world.item.ItemStack);
  public default boolean canBeHurtBy(net.minecraft.world.item.ItemStack, net.minecraft.world.damagesource.DamageSource);
  public default net.minecraft.world.item.ItemStack applyEnchantments(net.minecraft.world.item.ItemStack, java.util.List<net.minecraft.world.item.enchantment.EnchantmentInstance>);
  public default boolean canFitInsideContainerItems(net.minecraft.world.item.ItemStack);
}
