Compiled from "ClientHooks.java"
public class net.neoforged.neoforge.client.ClientHooks {
  public static java.lang.String forgeStatusLine;
  public net.neoforged.neoforge.client.ClientHooks();
  public static void resizeGuiLayers(net.minecraft.client.Minecraft, int, int);
  public static void clearGuiLayers(net.minecraft.client.Minecraft);
  public static void pushGuiLayer(net.minecraft.client.Minecraft, net.minecraft.client.gui.screens.Screen);
  public static void popGuiLayer(net.minecraft.client.Minecraft);
  public static float getGuiFarPlane();
  public static net.minecraft.resources.ResourceLocation getArmorTexture(net.minecraft.world.entity.Entity, net.minecraft.world.item.ItemStack, net.minecraft.world.item.ArmorMaterial$Layer, boolean, net.minecraft.world.entity.EquipmentSlot);
  public static boolean onClientPauseChangePre(boolean);
  public static void onClientPauseChangePost(boolean);
  public static boolean onDrawHighlight(net.minecraft.client.renderer.LevelRenderer, net.minecraft.client.Camera, net.minecraft.world.phys.HitResult, net.minecraft.client.DeltaTracker, com.mojang.blaze3d.vertex.PoseStack, net.minecraft.client.renderer.MultiBufferSource);
  public static void dispatchRenderStage(net.neoforged.neoforge.client.event.RenderLevelStageEvent$Stage, net.minecraft.client.renderer.LevelRenderer, com.mojang.blaze3d.vertex.PoseStack, org.joml.Matrix4f, org.joml.Matrix4f, int, net.minecraft.client.Camera, net.minecraft.client.renderer.culling.Frustum);
  public static void dispatchRenderStage(net.minecraft.client.renderer.RenderType, net.minecraft.client.renderer.LevelRenderer, org.joml.Matrix4f, org.joml.Matrix4f, int, net.minecraft.client.Camera, net.minecraft.client.renderer.culling.Frustum);
  public static boolean renderSpecificFirstPersonHand(net.minecraft.world.InteractionHand, com.mojang.blaze3d.vertex.PoseStack, net.minecraft.client.renderer.MultiBufferSource, int, float, float, float, float, net.minecraft.world.item.ItemStack);
  public static boolean renderSpecificFirstPersonArm(com.mojang.blaze3d.vertex.PoseStack, net.minecraft.client.renderer.MultiBufferSource, int, net.minecraft.client.player.AbstractClientPlayer, net.minecraft.world.entity.HumanoidArm);
  public static void onTextureAtlasStitched(net.minecraft.client.renderer.texture.TextureAtlas);
  public static void onBlockColorsInit(net.minecraft.client.color.block.BlockColors);
  public static void onItemColorsInit(net.minecraft.client.color.item.ItemColors, net.minecraft.client.color.block.BlockColors);
  public static net.minecraft.client.model.Model getArmorModel(net.minecraft.world.entity.LivingEntity, net.minecraft.world.item.ItemStack, net.minecraft.world.entity.EquipmentSlot, net.minecraft.client.model.HumanoidModel<?>);
  public static <T extends net.minecraft.world.entity.LivingEntity> void copyModelProperties(net.minecraft.client.model.HumanoidModel<T>, net.minecraft.client.model.HumanoidModel<?>);
  public static java.lang.String fixDomain(java.lang.String, java.lang.String);
  public static float getFieldOfViewModifier(net.minecraft.world.entity.player.Player, float);
  public static double getFieldOfView(net.minecraft.client.renderer.GameRenderer, net.minecraft.client.Camera, double, double, boolean);
  public static net.neoforged.neoforge.client.event.CalculatePlayerTurnEvent getTurnPlayerValues(double, boolean);
  public static float getDetachedCameraDistance(net.minecraft.client.Camera, boolean, float, float);
  public static void renderMainMenu(net.minecraft.client.gui.screens.TitleScreen, net.minecraft.client.gui.GuiGraphics, net.minecraft.client.gui.Font, int, int, int);
  public static net.minecraft.client.resources.sounds.SoundInstance playSound(net.minecraft.client.sounds.SoundEngine, net.minecraft.client.resources.sounds.SoundInstance);
  public static net.minecraft.sounds.Music selectMusic(net.minecraft.sounds.Music, net.minecraft.client.resources.sounds.SoundInstance);
  public static void drawScreen(net.minecraft.client.gui.screens.Screen, net.minecraft.client.gui.GuiGraphics, int, int, float);
  public static org.joml.Vector3f getFogColor(net.minecraft.client.Camera, float, net.minecraft.client.multiplayer.ClientLevel, int, float, float, float, float);
  public static void onFogRender(net.minecraft.client.renderer.FogRenderer$FogMode, net.minecraft.world.level.material.FogType, net.minecraft.client.Camera, float, float, float, float, com.mojang.blaze3d.shaders.FogShape);
  public static void onModifyBakingResult(java.util.Map<net.minecraft.client.resources.model.ModelResourceLocation, net.minecraft.client.resources.model.BakedModel>, java.util.Map<net.minecraft.resources.ResourceLocation, net.minecraft.client.resources.model.AtlasSet$StitchResult>, net.minecraft.client.resources.model.ModelBakery);
  public static void onModelBake(net.minecraft.client.resources.model.ModelManager, java.util.Map<net.minecraft.client.resources.model.ModelResourceLocation, net.minecraft.client.resources.model.BakedModel>, net.minecraft.client.resources.model.ModelBakery);
  public static net.minecraft.client.resources.model.BakedModel handleCameraTransforms(com.mojang.blaze3d.vertex.PoseStack, net.minecraft.client.resources.model.BakedModel, net.minecraft.world.item.ItemDisplayContext, boolean);
  public static net.minecraft.client.resources.model.Material getBlockMaterial(net.minecraft.resources.ResourceLocation);
  public static void fillNormal(int[], net.minecraft.core.Direction);
  public static boolean calculateFaceWithoutAO(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.world.level.block.state.BlockState, net.minecraft.core.BlockPos, net.minecraft.client.renderer.block.model.BakedQuad, boolean, float[], int[]);
  public static void loadEntityShader(net.minecraft.world.entity.Entity, net.minecraft.client.renderer.GameRenderer);
  public static boolean shouldCauseReequipAnimation(net.minecraft.world.item.ItemStack, net.minecraft.world.item.ItemStack, int);
  public static net.neoforged.neoforge.client.event.CustomizeGuiOverlayEvent$BossEventProgress onCustomizeBossEventProgress(net.minecraft.client.gui.GuiGraphics, com.mojang.blaze3d.platform.Window, net.minecraft.client.gui.components.LerpingBossEvent, int, int, int);
  public static net.neoforged.neoforge.client.event.ScreenshotEvent onScreenshot(com.mojang.blaze3d.platform.NativeImage, java.io.File);
  public static void onClientChangeGameType(net.minecraft.client.multiplayer.PlayerInfo, net.minecraft.world.level.GameType, net.minecraft.world.level.GameType);
  public static void onMovementInputUpdate(net.minecraft.world.entity.player.Player, net.minecraft.client.player.Input);
  public static boolean onScreenMouseClickedPre(net.minecraft.client.gui.screens.Screen, double, double, int);
  public static boolean onScreenMouseClickedPost(net.minecraft.client.gui.screens.Screen, double, double, int, boolean);
  public static boolean onScreenMouseReleasedPre(net.minecraft.client.gui.screens.Screen, double, double, int);
  public static boolean onScreenMouseReleasedPost(net.minecraft.client.gui.screens.Screen, double, double, int, boolean);
  public static boolean onScreenMouseDragPre(net.minecraft.client.gui.screens.Screen, double, double, int, double, double);
  public static void onScreenMouseDragPost(net.minecraft.client.gui.screens.Screen, double, double, int, double, double);
  public static boolean onScreenMouseScrollPre(net.minecraft.client.MouseHandler, net.minecraft.client.gui.screens.Screen, double, double);
  public static void onScreenMouseScrollPost(net.minecraft.client.MouseHandler, net.minecraft.client.gui.screens.Screen, double, double);
  public static boolean onScreenKeyPressedPre(net.minecraft.client.gui.screens.Screen, int, int, int);
  public static boolean onScreenKeyPressedPost(net.minecraft.client.gui.screens.Screen, int, int, int);
  public static boolean onScreenKeyReleasedPre(net.minecraft.client.gui.screens.Screen, int, int, int);
  public static boolean onScreenKeyReleasedPost(net.minecraft.client.gui.screens.Screen, int, int, int);
  public static boolean onScreenCharTypedPre(net.minecraft.client.gui.screens.Screen, char, int);
  public static void onScreenCharTypedPost(net.minecraft.client.gui.screens.Screen, char, int);
  public static void onRecipesUpdated(net.minecraft.world.item.crafting.RecipeManager);
  public static boolean onMouseButtonPre(int, int, int);
  public static void onMouseButtonPost(int, int, int);
  public static boolean onMouseScroll(net.minecraft.client.MouseHandler, double, double);
  public static void onKeyInput(int, int, int, int);
  public static net.neoforged.neoforge.client.event.InputEvent$InteractionKeyMappingTriggered onClickInput(int, net.minecraft.client.KeyMapping, net.minecraft.world.InteractionHand);
  public static boolean isNameplateInRenderDistance(net.minecraft.world.entity.Entity, double);
  public static void renderPistonMovedBlocks(net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, com.mojang.blaze3d.vertex.PoseStack, net.minecraft.client.renderer.MultiBufferSource, net.minecraft.world.level.Level, boolean, int, net.minecraft.client.renderer.block.BlockRenderDispatcher);
  public static boolean shouldRenderEffect(net.minecraft.world.effect.MobEffectInstance);
  public static void registerLayerDefinition(net.minecraft.client.model.geom.ModelLayerLocation, java.util.function.Supplier<net.minecraft.client.model.geom.builders.LayerDefinition>);
  public static void loadLayerDefinitions(com.google.common.collect.ImmutableMap$Builder<net.minecraft.client.model.geom.ModelLayerLocation, net.minecraft.client.model.geom.builders.LayerDefinition>);
  public static void firePlayerLogin(net.minecraft.client.multiplayer.MultiPlayerGameMode, net.minecraft.client.player.LocalPlayer, net.minecraft.network.Connection);
  public static void firePlayerLogout(net.minecraft.client.multiplayer.MultiPlayerGameMode, net.minecraft.client.player.LocalPlayer);
  public static void firePlayerRespawn(net.minecraft.client.multiplayer.MultiPlayerGameMode, net.minecraft.client.player.LocalPlayer, net.minecraft.client.player.LocalPlayer, net.minecraft.network.Connection);
  public static void onRegisterParticleProviders(net.minecraft.client.particle.ParticleEngine);
  public static void onRegisterKeyMappings(net.minecraft.client.Options);
  public static void onRegisterAdditionalModels(java.util.Set<net.minecraft.client.resources.model.ModelResourceLocation>);
  public static net.minecraft.network.chat.Component onClientChat(net.minecraft.network.chat.ChatType$Bound, net.minecraft.network.chat.Component, java.util.UUID);
  public static net.minecraft.network.chat.Component onClientPlayerChat(net.minecraft.network.chat.ChatType$Bound, net.minecraft.network.chat.Component, net.minecraft.network.chat.PlayerChatMessage, java.util.UUID);
  public static net.minecraft.network.chat.Component onClientSystemChat(net.minecraft.network.chat.Component, boolean);
  public static java.lang.String onClientSendMessage(java.lang.String);
  public static net.minecraft.client.renderer.RenderType getEntityRenderType(net.minecraft.client.renderer.RenderType, boolean);
  public static net.minecraft.client.gui.Font getTooltipFont(net.minecraft.world.item.ItemStack, net.minecraft.client.gui.Font);
  public static net.neoforged.neoforge.client.event.RenderTooltipEvent$Pre onRenderTooltipPre(net.minecraft.world.item.ItemStack, net.minecraft.client.gui.GuiGraphics, int, int, int, int, java.util.List<net.minecraft.client.gui.screens.inventory.tooltip.ClientTooltipComponent>, net.minecraft.client.gui.Font, net.minecraft.client.gui.screens.inventory.tooltip.ClientTooltipPositioner);
  public static net.neoforged.neoforge.client.event.RenderTooltipEvent$Color onRenderTooltipColor(net.minecraft.world.item.ItemStack, net.minecraft.client.gui.GuiGraphics, int, int, net.minecraft.client.gui.Font, java.util.List<net.minecraft.client.gui.screens.inventory.tooltip.ClientTooltipComponent>);
  public static java.util.List<net.minecraft.client.gui.screens.inventory.tooltip.ClientTooltipComponent> gatherTooltipComponents(net.minecraft.world.item.ItemStack, java.util.List<? extends net.minecraft.network.chat.FormattedText>, int, int, int, net.minecraft.client.gui.Font);
  public static java.util.List<net.minecraft.client.gui.screens.inventory.tooltip.ClientTooltipComponent> gatherTooltipComponents(net.minecraft.world.item.ItemStack, java.util.List<? extends net.minecraft.network.chat.FormattedText>, java.util.Optional<net.minecraft.world.inventory.tooltip.TooltipComponent>, int, int, int, net.minecraft.client.gui.Font);
  public static java.util.List<net.minecraft.client.gui.screens.inventory.tooltip.ClientTooltipComponent> gatherTooltipComponentsFromElements(net.minecraft.world.item.ItemStack, java.util.List<com.mojang.datafixers.util.Either<net.minecraft.network.chat.FormattedText, net.minecraft.world.inventory.tooltip.TooltipComponent>>, int, int, int, net.minecraft.client.gui.Font);
  public static java.util.Comparator<net.minecraft.client.particle.ParticleRenderType> makeParticleRenderTypeComparator(java.util.List<net.minecraft.client.particle.ParticleRenderType>);
  public static net.neoforged.neoforge.client.event.ScreenEvent$RenderInventoryMobEffects onScreenPotionSize(net.minecraft.client.gui.screens.Screen, int, boolean, int);
  public static boolean onToastAdd(net.minecraft.client.gui.components.toasts.Toast);
  public static boolean isBlockInSolidLayer(net.minecraft.world.level.block.state.BlockState);
  public static boolean renderFireOverlay(net.minecraft.world.entity.player.Player, com.mojang.blaze3d.vertex.PoseStack);
  public static boolean renderWaterOverlay(net.minecraft.world.entity.player.Player, com.mojang.blaze3d.vertex.PoseStack);
  public static boolean renderBlockOverlay(net.minecraft.world.entity.player.Player, com.mojang.blaze3d.vertex.PoseStack, net.neoforged.neoforge.client.event.RenderBlockScreenEffectEvent$OverlayType, net.minecraft.world.level.block.state.BlockState, net.minecraft.core.BlockPos);
  public static int getMaxMipmapLevel(int, int);
  public static net.minecraft.resources.ResourceLocation getShaderImportLocation(java.lang.String, boolean, java.lang.String);
  public static com.google.common.collect.BiMap<net.minecraft.resources.ResourceLocation, net.minecraft.client.renderer.texture.atlas.SpriteSourceType> makeSpriteSourceTypesMap();
  public static void registerSpriteSourceTypes();
  public static <T extends net.minecraft.world.level.block.entity.BlockEntity> boolean isBlockEntityRendererVisible(net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher, net.minecraft.world.level.block.entity.BlockEntity, net.minecraft.client.renderer.culling.Frustum);
  public static java.util.List<net.minecraft.client.renderer.block.model.BlockElement> fixItemModelSeams(java.util.List<net.minecraft.client.renderer.block.model.BlockElement>, net.minecraft.client.renderer.texture.TextureAtlasSprite);
  public static java.util.List<net.neoforged.neoforge.client.event.AddSectionGeometryEvent$AdditionalSectionRenderer> gatherAdditionalRenderers(net.minecraft.core.BlockPos, net.minecraft.world.level.Level);
  public static void addAdditionalGeometry(java.util.List<net.neoforged.neoforge.client.event.AddSectionGeometryEvent$AdditionalSectionRenderer>, java.util.function.Function<net.minecraft.client.renderer.RenderType, com.mojang.blaze3d.vertex.VertexConsumer>, net.minecraft.client.renderer.chunk.RenderChunkRegion, com.mojang.blaze3d.vertex.PoseStack);
  public static void initClientHooks(net.minecraft.client.Minecraft, net.minecraft.server.packs.resources.ReloadableResourceManager);
  public static void fireRenderFramePre(net.minecraft.client.DeltaTracker);
  public static void fireRenderFramePost(net.minecraft.client.DeltaTracker);
  public static void fireClientTickPre();
  public static void fireClientTickPost();
  public static <T> net.minecraft.core.HolderLookup$RegistryLookup<T> resolveLookup(net.minecraft.resources.ResourceKey<? extends net.minecraft.core.Registry<T>>);
  public static java.util.List<net.minecraft.network.chat.Component> getEffectTooltip(net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen<?>, net.minecraft.world.effect.MobEffectInstance, java.util.List<net.minecraft.network.chat.Component>);
  public static net.minecraft.world.inventory.RecipeBookType[] getFilteredRecipeBookTypeValues();
  public static void reloadRenderer();
  public static java.util.Map<net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation> gatherMaterialAtlases(java.util.Map<net.minecraft.resources.ResourceLocation, net.minecraft.resources.ResourceLocation>);
}
