Compiled from "ModModelTypes.java"
public final class com.minecolonies.api.client.render.modeltype.ModModelTypes {
  public static final net.minecraft.resources.ResourceLocation SETTLER_ID;
  public static final net.minecraft.resources.ResourceLocation CITIZEN_ID;
  public static final net.minecraft.resources.ResourceLocation NOBLE_ID;
  public static final net.minecraft.resources.ResourceLocation ARISTOCRAT_ID;
  public static final net.minecraft.resources.ResourceLocation BUILDER_ID;
  public static final net.minecraft.resources.ResourceLocation COURIER_ID;
  public static final net.minecraft.resources.ResourceLocation MINER_ID;
  public static final net.minecraft.resources.ResourceLocation LUMBERJACK_ID;
  public static final net.minecraft.resources.ResourceLocation FARMER_ID;
  public static final net.minecraft.resources.ResourceLocation FISHERMAN_ID;
  public static final net.minecraft.resources.ResourceLocation UNDERTAKER_ID;
  public static final net.minecraft.resources.ResourceLocation ARCHER_GUARD_ID;
  public static final net.minecraft.resources.ResourceLocation KNIGHT_GUARD_ID;
  public static final net.minecraft.resources.ResourceLocation BAKER_ID;
  public static final net.minecraft.resources.ResourceLocation SHEEP_FARMER_ID;
  public static final net.minecraft.resources.ResourceLocation COW_FARMER_ID;
  public static final net.minecraft.resources.ResourceLocation PIG_FARMER_ID;
  public static final net.minecraft.resources.ResourceLocation CHICKEN_FARMER_ID;
  public static final net.minecraft.resources.ResourceLocation COMPOSTER_ID;
  public static final net.minecraft.resources.ResourceLocation SMELTER_ID;
  public static final net.minecraft.resources.ResourceLocation COOK_ID;
  public static final net.minecraft.resources.ResourceLocation STUDENT_ID;
  public static final net.minecraft.resources.ResourceLocation CRAFTER_ID;
  public static final net.minecraft.resources.ResourceLocation BLACKSMITH_ID;
  public static final net.minecraft.resources.ResourceLocation CHILD_ID;
  public static final net.minecraft.resources.ResourceLocation HEALER_ID;
  public static final net.minecraft.resources.ResourceLocation TEACHER_ID;
  public static final net.minecraft.resources.ResourceLocation GLASSBLOWER_ID;
  public static final net.minecraft.resources.ResourceLocation DYER_ID;
  public static final net.minecraft.resources.ResourceLocation MECHANIST_ID;
  public static final net.minecraft.resources.ResourceLocation FLETCHER_ID;
  public static final net.minecraft.resources.ResourceLocation CONCRETE_MIXER_ID;
  public static final net.minecraft.resources.ResourceLocation RABBIT_HERDER_ID;
  public static final net.minecraft.resources.ResourceLocation PLANTER_ID;
  public static final net.minecraft.resources.ResourceLocation BEEKEEPER_ID;
  public static final net.minecraft.resources.ResourceLocation CUSTOM_ID;
  public static final net.minecraft.resources.ResourceLocation NETHERWORKER_ID;
  public static final net.minecraft.resources.ResourceLocation DRUID_ID;
  public static final net.minecraft.resources.ResourceLocation ENCHANTER_ID;
  public static final net.minecraft.resources.ResourceLocation FLORIST_ID;
  public static final net.minecraft.resources.ResourceLocation KNIGHT_ID;
  public static final net.minecraft.resources.ResourceLocation CARPENTER_ID;
  public static final net.minecraft.resources.ResourceLocation ALCHEMIST_ID;
  public static com.minecolonies.api.client.render.modeltype.IModelType SETTLER;
  public static com.minecolonies.api.client.render.modeltype.IModelType CITIZEN;
  public static com.minecolonies.api.client.render.modeltype.IModelType NOBLE;
  public static com.minecolonies.api.client.render.modeltype.IModelType ARISTOCRAT;
  public static com.minecolonies.api.client.render.modeltype.IModelType BUILDER;
  public static com.minecolonies.api.client.render.modeltype.IModelType DELIVERYMAN;
  public static com.minecolonies.api.client.render.modeltype.IModelType MINER;
  public static com.minecolonies.api.client.render.modeltype.IModelType LUMBERJACK;
  public static com.minecolonies.api.client.render.modeltype.IModelType FARMER;
  public static com.minecolonies.api.client.render.modeltype.IModelType FISHERMAN;
  public static com.minecolonies.api.client.render.modeltype.IModelType UNDERTAKER;
  public static com.minecolonies.api.client.render.modeltype.IModelType ARCHER_GUARD;
  public static com.minecolonies.api.client.render.modeltype.IModelType KNIGHT_GUARD;
  public static com.minecolonies.api.client.render.modeltype.IModelType BAKER;
  public static com.minecolonies.api.client.render.modeltype.IModelType SHEEP_FARMER;
  public static com.minecolonies.api.client.render.modeltype.IModelType COW_FARMER;
  public static com.minecolonies.api.client.render.modeltype.IModelType PIG_FARMER;
  public static com.minecolonies.api.client.render.modeltype.IModelType CHICKEN_FARMER;
  public static com.minecolonies.api.client.render.modeltype.IModelType COMPOSTER;
  public static com.minecolonies.api.client.render.modeltype.IModelType SMELTER;
  public static com.minecolonies.api.client.render.modeltype.IModelType COOK;
  public static com.minecolonies.api.client.render.modeltype.IModelType STUDENT;
  public static com.minecolonies.api.client.render.modeltype.IModelType CRAFTER;
  public static com.minecolonies.api.client.render.modeltype.IModelType BLACKSMITH;
  public static com.minecolonies.api.client.render.modeltype.IModelType CHILD;
  public static com.minecolonies.api.client.render.modeltype.IModelType HEALER;
  public static com.minecolonies.api.client.render.modeltype.IModelType TEACHER;
  public static com.minecolonies.api.client.render.modeltype.IModelType GLASSBLOWER;
  public static com.minecolonies.api.client.render.modeltype.IModelType DYER;
  public static com.minecolonies.api.client.render.modeltype.IModelType MECHANIST;
  public static com.minecolonies.api.client.render.modeltype.IModelType FLETCHER;
  public static com.minecolonies.api.client.render.modeltype.IModelType CONCRETE_MIXER;
  public static com.minecolonies.api.client.render.modeltype.IModelType RABBIT_HERDER;
  public static com.minecolonies.api.client.render.modeltype.IModelType PLANTER;
  public static com.minecolonies.api.client.render.modeltype.IModelType BEEKEEPER;
  public static com.minecolonies.api.client.render.modeltype.IModelType CUSTOM;
  public static com.minecolonies.api.client.render.modeltype.IModelType NETHERWORKER;
  public static com.minecolonies.api.client.render.modeltype.IModelType DRUID;
  public static com.minecolonies.api.client.render.modeltype.IModelType FLORIST;
  public static com.minecolonies.api.client.render.modeltype.IModelType ENCHANTER;
  public static com.minecolonies.api.client.render.modeltype.IModelType KNIGHT;
  public static com.minecolonies.api.client.render.modeltype.IModelType CARPENTER;
  public static com.minecolonies.api.client.render.modeltype.IModelType ALCHEMIST;
}
