Compiled from "EventHooks.java"
public class net.neoforged.neoforge.event.EventHooks {
  public net.neoforged.neoforge.event.EventHooks();
  public static boolean onMultiBlockPlace(net.minecraft.world.entity.Entity, java.util.List<net.neoforged.neoforge.common.util.BlockSnapshot>, net.minecraft.core.Direction);
  public static boolean onBlockPlace(net.minecraft.world.entity.Entity, net.neoforged.neoforge.common.util.BlockSnapshot, net.minecraft.core.Direction);
  public static net.neoforged.neoforge.event.level.BlockEvent$NeighborNotifyEvent onNeighborNotify(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, java.util.EnumSet<net.minecraft.core.Direction>, boolean);
  public static boolean doPlayerHarvestCheck(net.minecraft.world.entity.player.Player, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos);
  public static float getBreakSpeed(net.minecraft.world.entity.player.Player, net.minecraft.world.level.block.state.BlockState, float, net.minecraft.core.BlockPos);
  public static void onPlayerDestroyItem(net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack, net.minecraft.world.InteractionHand);
  public static boolean checkSpawnPlacements(net.minecraft.world.entity.EntityType<?>, net.minecraft.world.level.ServerLevelAccessor, net.minecraft.world.entity.MobSpawnType, net.minecraft.core.BlockPos, net.minecraft.util.RandomSource, boolean);
  public static boolean checkSpawnPosition(net.minecraft.world.entity.Mob, net.minecraft.world.level.ServerLevelAccessor, net.minecraft.world.entity.MobSpawnType);
  public static boolean checkSpawnPositionSpawner(net.minecraft.world.entity.Mob, net.minecraft.world.level.ServerLevelAccessor, net.minecraft.world.entity.MobSpawnType, net.minecraft.world.level.SpawnData, net.minecraft.world.level.BaseSpawner);
  public static net.minecraft.world.entity.SpawnGroupData finalizeMobSpawn(net.minecraft.world.entity.Mob, net.minecraft.world.level.ServerLevelAccessor, net.minecraft.world.DifficultyInstance, net.minecraft.world.entity.MobSpawnType, net.minecraft.world.entity.SpawnGroupData);
  public static net.neoforged.neoforge.event.entity.living.FinalizeSpawnEvent finalizeMobSpawnSpawner(net.minecraft.world.entity.Mob, net.minecraft.world.level.ServerLevelAccessor, net.minecraft.world.DifficultyInstance, net.minecraft.world.entity.MobSpawnType, net.minecraft.world.entity.SpawnGroupData, net.neoforged.neoforge.common.extensions.IOwnedSpawner, boolean);
  public static net.neoforged.neoforge.event.entity.player.PlayerSpawnPhantomsEvent firePlayerSpawnPhantoms(net.minecraft.server.level.ServerPlayer, net.minecraft.server.level.ServerLevel, net.minecraft.core.BlockPos);
  public static boolean checkMobDespawn(net.minecraft.world.entity.Mob);
  public static int getItemBurnTime(net.minecraft.world.item.ItemStack, int, net.minecraft.world.item.crafting.RecipeType<?>);
  public static int getExperienceDrop(net.minecraft.world.entity.LivingEntity, net.minecraft.world.entity.player.Player, int);
  public static int getMaxSpawnClusterSize(net.minecraft.world.entity.Mob);
  public static net.minecraft.network.chat.Component getPlayerDisplayName(net.minecraft.world.entity.player.Player, net.minecraft.network.chat.Component);
  public static net.minecraft.network.chat.Component getPlayerTabListDisplayName(net.minecraft.world.entity.player.Player);
  public static net.minecraft.world.level.block.state.BlockState fireFluidPlaceBlockEvent(net.minecraft.world.level.LevelAccessor, net.minecraft.core.BlockPos, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState);
  public static net.neoforged.neoforge.event.entity.player.ItemTooltipEvent onItemTooltip(net.minecraft.world.item.ItemStack, net.minecraft.world.entity.player.Player, java.util.List<net.minecraft.network.chat.Component>, net.minecraft.world.item.TooltipFlag, net.minecraft.world.item.Item$TooltipContext);
  public static boolean onEntityStruckByLightning(net.minecraft.world.entity.Entity, net.minecraft.world.entity.LightningBolt);
  public static int onItemUseStart(net.minecraft.world.entity.LivingEntity, net.minecraft.world.item.ItemStack, int);
  public static int onItemUseStart(net.minecraft.world.entity.LivingEntity, net.minecraft.world.item.ItemStack, net.minecraft.world.InteractionHand, int);
  public static int onItemUseTick(net.minecraft.world.entity.LivingEntity, net.minecraft.world.item.ItemStack, int);
  public static boolean onUseItemStop(net.minecraft.world.entity.LivingEntity, net.minecraft.world.item.ItemStack, int);
  public static net.minecraft.world.item.ItemStack onItemUseFinish(net.minecraft.world.entity.LivingEntity, net.minecraft.world.item.ItemStack, int, net.minecraft.world.item.ItemStack);
  public static void onStartEntityTracking(net.minecraft.world.entity.Entity, net.minecraft.world.entity.player.Player);
  public static void onStopEntityTracking(net.minecraft.world.entity.Entity, net.minecraft.world.entity.player.Player);
  public static void firePlayerLoadingEvent(net.minecraft.world.entity.player.Player, java.io.File, java.lang.String);
  public static void firePlayerSavingEvent(net.minecraft.world.entity.player.Player, java.io.File, java.lang.String);
  public static void firePlayerLoadingEvent(net.minecraft.world.entity.player.Player, net.minecraft.world.level.storage.PlayerDataStorage, java.lang.String);
  public static net.minecraft.world.level.block.state.BlockState onToolUse(net.minecraft.world.level.block.state.BlockState, net.minecraft.world.item.context.UseOnContext, net.neoforged.neoforge.common.ItemAbility, boolean);
  public static net.neoforged.neoforge.event.entity.player.BonemealEvent fireBonemealEvent(net.minecraft.world.entity.player.Player, net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.world.item.ItemStack);
  public static net.neoforged.neoforge.event.PlayLevelSoundEvent$AtEntity onPlaySoundAtEntity(net.minecraft.world.entity.Entity, net.minecraft.core.Holder<net.minecraft.sounds.SoundEvent>, net.minecraft.sounds.SoundSource, float, float);
  public static net.neoforged.neoforge.event.PlayLevelSoundEvent$AtPosition onPlaySoundAtPosition(net.minecraft.world.level.Level, double, double, double, net.minecraft.core.Holder<net.minecraft.sounds.SoundEvent>, net.minecraft.sounds.SoundSource, float, float);
  public static int onItemExpire(net.minecraft.world.entity.item.ItemEntity);
  public static net.neoforged.neoforge.event.entity.player.ItemEntityPickupEvent$Pre fireItemPickupPre(net.minecraft.world.entity.item.ItemEntity, net.minecraft.world.entity.player.Player);
  public static void fireItemPickupPost(net.minecraft.world.entity.item.ItemEntity, net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack);
  public static boolean canMountEntity(net.minecraft.world.entity.Entity, net.minecraft.world.entity.Entity, boolean);
  public static boolean onAnimalTame(net.minecraft.world.entity.animal.Animal, net.minecraft.world.entity.player.Player);
  public static com.mojang.datafixers.util.Either<net.minecraft.world.entity.player.Player$BedSleepingProblem, net.minecraft.util.Unit> canPlayerStartSleeping(net.minecraft.server.level.ServerPlayer, net.minecraft.core.BlockPos, com.mojang.datafixers.util.Either<net.minecraft.world.entity.player.Player$BedSleepingProblem, net.minecraft.util.Unit>);
  public static void onPlayerWakeup(net.minecraft.world.entity.player.Player, boolean, boolean);
  public static void onPlayerFall(net.minecraft.world.entity.player.Player, float, float);
  public static boolean onPlayerSpawnSet(net.minecraft.world.entity.player.Player, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>, net.minecraft.core.BlockPos, boolean);
  public static void onPlayerClone(net.minecraft.world.entity.player.Player, net.minecraft.world.entity.player.Player, boolean);
  public static boolean onExplosionStart(net.minecraft.world.level.Level, net.minecraft.world.level.Explosion);
  public static void onExplosionDetonate(net.minecraft.world.level.Level, net.minecraft.world.level.Explosion, java.util.List<net.minecraft.world.entity.Entity>, double);
  public static net.minecraft.world.phys.Vec3 getExplosionKnockback(net.minecraft.world.level.Level, net.minecraft.world.level.Explosion, net.minecraft.world.entity.Entity, net.minecraft.world.phys.Vec3);
  public static boolean onCreateWorldSpawn(net.minecraft.world.level.Level, net.minecraft.world.level.storage.ServerLevelData);
  public static float onLivingHeal(net.minecraft.world.entity.LivingEntity, float);
  public static boolean onPotionAttemptBrew(net.minecraft.core.NonNullList<net.minecraft.world.item.ItemStack>);
  public static void onPotionBrewed(net.minecraft.core.NonNullList<net.minecraft.world.item.ItemStack>);
  public static void onPlayerBrewedPotion(net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack);
  public static boolean canEntityContinueSleeping(net.minecraft.world.entity.LivingEntity, net.minecraft.world.entity.player.Player$BedSleepingProblem);
  public static net.minecraft.world.InteractionResultHolder<net.minecraft.world.item.ItemStack> onArrowNock(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level, net.minecraft.world.entity.player.Player, net.minecraft.world.InteractionHand, boolean);
  public static int onArrowLoose(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level, net.minecraft.world.entity.player.Player, int, boolean);
  public static boolean onProjectileImpact(net.minecraft.world.entity.projectile.Projectile, net.minecraft.world.phys.HitResult);
  public static net.minecraft.world.level.storage.loot.LootTable loadLootTable(net.minecraft.resources.ResourceLocation, net.minecraft.world.level.storage.loot.LootTable);
  public static net.minecraft.world.level.storage.loot.LootTable loadLootTable(net.minecraft.core.HolderLookup$Provider, net.minecraft.resources.ResourceLocation, net.minecraft.world.level.storage.loot.LootTable);
  public static boolean canCreateFluidSource(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState);
  public static java.util.Optional<net.minecraft.world.level.portal.PortalShape> onTrySpawnPortal(net.minecraft.world.level.LevelAccessor, net.minecraft.core.BlockPos, java.util.Optional<net.minecraft.world.level.portal.PortalShape>);
  public static int onEnchantmentLevelSet(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, int, int, net.minecraft.world.item.ItemStack, int);
  public static boolean onEntityDestroyBlock(net.minecraft.world.entity.LivingEntity, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState);
  public static boolean canEntityGrief(net.minecraft.world.level.Level, net.minecraft.world.entity.Entity);
  public static net.neoforged.neoforge.event.level.BlockGrowFeatureEvent fireBlockGrowFeature(net.minecraft.world.level.LevelAccessor, net.minecraft.util.RandomSource, net.minecraft.core.BlockPos, net.minecraft.core.Holder<net.minecraft.world.level.levelgen.feature.ConfiguredFeature<?, ?>>);
  public static net.neoforged.neoforge.event.level.AlterGroundEvent$StateProvider alterGround(net.minecraft.world.level.levelgen.feature.treedecorators.TreeDecorator$Context, java.util.List<net.minecraft.core.BlockPos>, net.neoforged.neoforge.event.level.AlterGroundEvent$StateProvider);
  public static void fireChunkTicketLevelUpdated(net.minecraft.server.level.ServerLevel, long, int, int, net.minecraft.server.level.ChunkHolder);
  public static void fireChunkWatch(net.minecraft.server.level.ServerPlayer, net.minecraft.world.level.chunk.LevelChunk, net.minecraft.server.level.ServerLevel);
  public static void fireChunkSent(net.minecraft.server.level.ServerPlayer, net.minecraft.world.level.chunk.LevelChunk, net.minecraft.server.level.ServerLevel);
  public static void fireChunkUnWatch(net.minecraft.server.level.ServerPlayer, net.minecraft.world.level.ChunkPos, net.minecraft.server.level.ServerLevel);
  public static boolean onPistonMovePre(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.core.Direction, boolean);
  public static void onPistonMovePost(net.minecraft.world.level.Level, net.minecraft.core.BlockPos, net.minecraft.core.Direction, boolean);
  public static long onSleepFinished(net.minecraft.server.level.ServerLevel, long, long);
  public static java.util.List<net.minecraft.server.packs.resources.PreparableReloadListener> onResourceReload(net.minecraft.server.ReloadableServerResources, net.minecraft.core.RegistryAccess);
  public static void onCommandRegister(com.mojang.brigadier.CommandDispatcher<net.minecraft.commands.CommandSourceStack>, net.minecraft.commands.Commands$CommandSelection, net.minecraft.commands.CommandBuildContext);
  public static net.neoforged.neoforge.event.entity.EntityEvent$Size getEntitySizeForge(net.minecraft.world.entity.Entity, net.minecraft.world.entity.Pose, net.minecraft.world.entity.EntityDimensions);
  public static net.neoforged.neoforge.event.entity.EntityEvent$Size getEntitySizeForge(net.minecraft.world.entity.Entity, net.minecraft.world.entity.Pose, net.minecraft.world.entity.EntityDimensions, net.minecraft.world.entity.EntityDimensions);
  public static boolean canLivingConvert(net.minecraft.world.entity.LivingEntity, net.minecraft.world.entity.EntityType<? extends net.minecraft.world.entity.LivingEntity>, java.util.function.Consumer<java.lang.Integer>);
  public static void onLivingConvert(net.minecraft.world.entity.LivingEntity, net.minecraft.world.entity.LivingEntity);
  public static net.neoforged.neoforge.event.entity.EntityTeleportEvent$TeleportCommand onEntityTeleportCommand(net.minecraft.world.entity.Entity, double, double, double);
  public static net.neoforged.neoforge.event.entity.EntityTeleportEvent$SpreadPlayersCommand onEntityTeleportSpreadPlayersCommand(net.minecraft.world.entity.Entity, double, double, double);
  public static net.neoforged.neoforge.event.entity.EntityTeleportEvent$EnderEntity onEnderTeleport(net.minecraft.world.entity.LivingEntity, double, double, double);
  public static net.neoforged.neoforge.event.entity.EntityTeleportEvent$EnderPearl onEnderPearlLand(net.minecraft.server.level.ServerPlayer, double, double, double, net.minecraft.world.entity.projectile.ThrownEnderpearl, float, net.minecraft.world.phys.HitResult);
  public static net.neoforged.neoforge.event.entity.EntityTeleportEvent$ChorusFruit onChorusFruitTeleport(net.minecraft.world.entity.LivingEntity, double, double, double);
  public static boolean onPermissionChanged(com.mojang.authlib.GameProfile, int, net.minecraft.server.players.PlayerList);
  public static void firePlayerChangedDimensionEvent(net.minecraft.world.entity.player.Player, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>, net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>);
  public static void firePlayerLoggedIn(net.minecraft.world.entity.player.Player);
  public static void firePlayerLoggedOut(net.minecraft.world.entity.player.Player);
  public static net.neoforged.neoforge.event.entity.player.PlayerRespawnPositionEvent firePlayerRespawnPositionEvent(net.minecraft.server.level.ServerPlayer, net.minecraft.world.level.portal.DimensionTransition, boolean);
  public static void firePlayerRespawnEvent(net.minecraft.server.level.ServerPlayer, boolean);
  public static void firePlayerCraftingEvent(net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack, net.minecraft.world.Container);
  public static void firePlayerSmeltedEvent(net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack);
  public static net.minecraft.client.gui.Gui$HeartType firePlayerHeartTypeEvent(net.minecraft.world.entity.player.Player, net.minecraft.client.gui.Gui$HeartType);
  public static net.neoforged.neoforge.event.tick.EntityTickEvent$Pre fireEntityTickPre(net.minecraft.world.entity.Entity);
  public static void fireEntityTickPost(net.minecraft.world.entity.Entity);
  public static void firePlayerTickPre(net.minecraft.world.entity.player.Player);
  public static void firePlayerTickPost(net.minecraft.world.entity.player.Player);
  public static void fireLevelTickPre(net.minecraft.world.level.Level, java.util.function.BooleanSupplier);
  public static void fireLevelTickPost(net.minecraft.world.level.Level, java.util.function.BooleanSupplier);
  public static void fireServerTickPre(java.util.function.BooleanSupplier, net.minecraft.server.MinecraftServer);
  public static void fireServerTickPost(java.util.function.BooleanSupplier, net.minecraft.server.MinecraftServer);
  public static net.minecraft.util.random.WeightedRandomList<net.minecraft.world.level.biome.MobSpawnSettings$SpawnerData> getPotentialSpawns(net.minecraft.world.level.LevelAccessor, net.minecraft.world.entity.MobCategory, net.minecraft.core.BlockPos, net.minecraft.util.random.WeightedRandomList<net.minecraft.world.level.biome.MobSpawnSettings$SpawnerData>);
  public static net.neoforged.neoforge.event.StatAwardEvent onStatAward(net.minecraft.world.entity.player.Player, net.minecraft.stats.Stat<?>, int);
  public static void onAdvancementEarnedEvent(net.minecraft.world.entity.player.Player, net.minecraft.advancements.AdvancementHolder);
  public static void onAdvancementProgressedEvent(net.minecraft.world.entity.player.Player, net.minecraft.advancements.AdvancementHolder, net.minecraft.advancements.AdvancementProgress, java.lang.String, net.neoforged.neoforge.event.entity.player.AdvancementEvent$AdvancementProgressEvent$ProgressType);
  public static boolean onEffectRemoved(net.minecraft.world.entity.LivingEntity, net.minecraft.core.Holder<net.minecraft.world.effect.MobEffect>, net.neoforged.neoforge.common.EffectCure);
  public static boolean onEffectRemoved(net.minecraft.world.entity.LivingEntity, net.minecraft.world.effect.MobEffectInstance, net.neoforged.neoforge.common.EffectCure);
  public static int getEnchantmentLevelSpecific(int, net.minecraft.world.item.ItemStack, net.minecraft.core.Holder<net.minecraft.world.item.enchantment.Enchantment>);
  public static net.minecraft.world.item.enchantment.ItemEnchantments getAllEnchantmentLevels(net.minecraft.world.item.enchantment.ItemEnchantments, net.minecraft.world.item.ItemStack, net.minecraft.core.HolderLookup$RegistryLookup<net.minecraft.world.item.enchantment.Enchantment>);
  public static void onCreativeModeTabBuildContents(net.minecraft.world.item.CreativeModeTab, net.minecraft.resources.ResourceKey<net.minecraft.world.item.CreativeModeTab>, net.minecraft.world.item.CreativeModeTab$DisplayItemsGenerator, net.minecraft.world.item.CreativeModeTab$ItemDisplayParameters, net.minecraft.world.item.CreativeModeTab$Output);
  public static net.neoforged.neoforge.event.entity.living.MobSplitEvent onMobSplit(net.minecraft.world.entity.Mob, java.util.List<net.minecraft.world.entity.Mob>);
  public static java.util.List<net.minecraft.world.level.CustomSpawner> getCustomSpawners(net.minecraft.server.level.ServerLevel, java.util.List<net.minecraft.world.level.CustomSpawner>);
}
